declare namespace RageEnums.Vehicle {
	/** [https://wiki.rage.mp/index.php?title=Vehicle_Bones](https://wiki.rage.mp/index.php?title=Vehicle_Bones) */
	const enum Bones {
		CHASSIS = 'chassis',
		CHASSIS_LOWLOD = 'chassis_lowlod',
		CHASSIS_DUMMY = 'chassis_dummy',
		SEAT_DSIDE_F = 'seat_dside_f',
		SEAT_DSIDE_R = 'seat_dside_r',
		SEAT_DSIDE_R1 = 'seat_dside_r1',
		SEAT_DSIDE_R2 = 'seat_dside_r2',
		SEAT_DSIDE_R3 = 'seat_dside_r3',
		SEAT_DSIDE_R4 = 'seat_dside_r4',
		SEAT_DSIDE_R5 = 'seat_dside_r5',
		SEAT_DSIDE_R6 = 'seat_dside_r6',
		SEAT_DSIDE_R7 = 'seat_dside_r7',
		SEAT_PSIDE_F = 'seat_pside_f',
		SEAT_PSIDE_R = 'seat_pside_r',
		SEAT_PSIDE_R1 = 'seat_pside_r1',
		SEAT_PSIDE_R2 = 'seat_pside_r2',
		SEAT_PSIDE_R3 = 'seat_pside_r3',
		SEAT_PSIDE_R4 = 'seat_pside_r4',
		SEAT_PSIDE_R5 = 'seat_pside_r5',
		SEAT_PSIDE_R6 = 'seat_pside_r6',
		SEAT_PSIDE_R7 = 'seat_pside_r7',
		WINDOW_LF1 = 'window_lf1',
		WINDOW_LF2 = 'window_lf2',
		WINDOW_LF3 = 'window_lf3',
		WINDOW_RF1 = 'window_rf1',
		WINDOW_RF2 = 'window_rf2',
		WINDOW_RF3 = 'window_rf3',
		WINDOW_LR1 = 'window_lr1',
		WINDOW_LR2 = 'window_lr2',
		WINDOW_LR3 = 'window_lr3',
		WINDOW_RR1 = 'window_rr1',
		WINDOW_RR2 = 'window_rr2',
		WINDOW_RR3 = 'window_rr3',
		DOOR_DSIDE_F = 'door_dside_f',
		DOOR_DSIDE_R = 'door_dside_r',
		DOOR_PSIDE_F = 'door_pside_f',
		DOOR_PSIDE_R = 'door_pside_r',
		HANDLE_DSIDE_F = 'handle_dside_f',
		HANDLE_DSIDE_R = 'handle_dside_r',
		HANDLE_PSIDE_F = 'handle_pside_f',
		HANDLE_PSIDE_R = 'handle_pside_r',
		WHEEL_LF = 'wheel_lf',
		WHEEL_RF = 'wheel_rf',
		WHEEL_LM1 = 'wheel_lm1',
		WHEEL_RM1 = 'wheel_rm1',
		WHEEL_LM2 = 'wheel_lm2',
		WHEEL_RM2 = 'wheel_rm2',
		WHEEL_LM3 = 'wheel_lm3',
		WHEEL_RM3 = 'wheel_rm3',
		WHEEL_LR = 'wheel_lr',
		WHEEL_RR = 'wheel_rr',
		SUSPENSION_LF = 'suspension_lf',
		SUSPENSION_RF = 'suspension_rf',
		SUSPENSION_LM = 'suspension_lm',
		SUSPENSION_RM = 'suspension_rm',
		SUSPENSION_LR = 'suspension_lr',
		SUSPENSION_RR = 'suspension_rr',
		SPRING_RF = 'spring_rf',
		SPRING_LF = 'spring_lf',
		SPRING_RR = 'spring_rr',
		SPRING_LR = 'spring_lr',
		TRANSMISSION_F = 'transmission_f',
		TRANSMISSION_M = 'transmission_m',
		TRANSMISSION_R = 'transmission_r',
		HUB_LF = 'hub_lf',
		HUB_RF = 'hub_rf',
		HUB_LM1 = 'hub_lm1',
		HUB_RM1 = 'hub_rm1',
		HUB_LM2 = 'hub_lm2',
		HUB_RM2 = 'hub_rm2',
		HUB_LM3 = 'hub_lm3',
		HUB_RM3 = 'hub_rm3',
		HUB_LR = 'hub_lr',
		HUB_RR = 'hub_rr',
		WINDSCREEN = 'windscreen',
		WINDSCREEN_R = 'windscreen_r',
		WINDOW_LF = 'window_lf',
		WINDOW_RF = 'window_rf',
		WINDOW_LR = 'window_lr',
		WINDOW_RR = 'window_rr',
		WINDOW_LM = 'window_lm',
		WINDOW_RM = 'window_rm',
		BODYSHELL = 'bodyshell',
		BUMPER_F = 'bumper_f',
		BUMPER_R = 'bumper_r',
		WING_RF = 'wing_rf',
		WING_LF = 'wing_lf',
		BONNET = 'bonnet',
		BOOT = 'boot',
		EXHAUST = 'exhaust',
		EXHAUST_2 = 'exhaust_2',
		EXHAUST_3 = 'exhaust_3',
		EXHAUST_4 = 'exhaust_4',
		EXHAUST_5 = 'exhaust_5',
		EXHAUST_6 = 'exhaust_6',
		EXHAUST_7 = 'exhaust_7',
		EXHAUST_8 = 'exhaust_8',
		EXHAUST_9 = 'exhaust_9',
		EXHAUST_10 = 'exhaust_10',
		EXHAUST_11 = 'exhaust_11',
		EXHAUST_12 = 'exhaust_12',
		EXHAUST_13 = 'exhaust_13',
		EXHAUST_14 = 'exhaust_14',
		EXHAUST_15 = 'exhaust_15',
		EXHAUST_16 = 'exhaust_16',
		ENGINE = 'engine',
		OVERHEAT = 'overheat',
		OVERHEAT_2 = 'overheat_2',
		PETROLCAP = 'petrolcap',
		PETROLTANK = 'petroltank',
		PETROLTANK_L = 'petroltank_l',
		PETROLTANK_R = 'petroltank_r',
		STEERING = 'steering',
		HBGRIP_L = 'hbgrip_l',
		HBGRIP_R = 'hbgrip_r',
		HEADLIGHT_L = 'headlight_l',
		HEADLIGHT_R = 'headlight_r',
		TAILLIGHT_L = 'taillight_l',
		TAILLIGHT_R = 'taillight_r',
		INDICATOR_LF = 'indicator_lf',
		INDICATOR_RF = 'indicator_rf',
		INDICATOR_LR = 'indicator_lr',
		INDICATOR_RR = 'indicator_rr',
		BRAKELIGHT_L = 'brakelight_l',
		BRAKELIGHT_R = 'brakelight_r',
		BRAKELIGHT_M = 'brakelight_m',
		REVERSINGLIGHT_L = 'reversinglight_l',
		REVERSINGLIGHT_R = 'reversinglight_r',
		EXTRALIGHT_1 = 'extralight_1',
		EXTRALIGHT_2 = 'extralight_2',
		EXTRALIGHT_3 = 'extralight_3',
		EXTRALIGHT_4 = 'extralight_4',
		NUMBERPLATE = 'numberplate',
		INTERIORLIGHT = 'interiorlight',
		SIREN1 = 'siren1',
		SIREN2 = 'siren2',
		SIREN3 = 'siren3',
		SIREN4 = 'siren4',
		SIREN5 = 'siren5',
		SIREN6 = 'siren6',
		SIREN7 = 'siren7',
		SIREN8 = 'siren8',
		SIREN9 = 'siren9',
		SIREN10 = 'siren10',
		SIREN11 = 'siren11',
		SIREN12 = 'siren12',
		SIREN13 = 'siren13',
		SIREN14 = 'siren14',
		SIREN15 = 'siren15',
		SIREN16 = 'siren16',
		SIREN17 = 'siren17',
		SIREN18 = 'siren18',
		SIREN19 = 'siren19',
		SIREN20 = 'siren20',
		SIREN_GLASS1 = 'siren_glass1',
		SIREN_GLASS2 = 'siren_glass2',
		SIREN_GLASS3 = 'siren_glass3',
		SIREN_GLASS4 = 'siren_glass4',
		SIREN_GLASS5 = 'siren_glass5',
		SIREN_GLASS6 = 'siren_glass6',
		SIREN_GLASS7 = 'siren_glass7',
		SIREN_GLASS8 = 'siren_glass8',
		SIREN_GLASS9 = 'siren_glass9',
		SIREN_GLASS10 = 'siren_glass10',
		SIREN_GLASS11 = 'siren_glass11',
		SIREN_GLASS12 = 'siren_glass12',
		SIREN_GLASS13 = 'siren_glass13',
		SIREN_GLASS14 = 'siren_glass14',
		SIREN_GLASS15 = 'siren_glass15',
		SIREN_GLASS16 = 'siren_glass16',
		SIREN_GLASS17 = 'siren_glass17',
		SIREN_GLASS18 = 'siren_glass18',
		SIREN_GLASS19 = 'siren_glass19',
		SIREN_GLASS20 = 'siren_glass20',
		SPOILER = 'spoiler',
		STRUTS = 'struts',
		MISC_A = 'misc_a',
		MISC_B = 'misc_b',
		MISC_C = 'misc_c',
		MISC_D = 'misc_d',
		MISC_E = 'misc_e',
		MISC_F = 'misc_f',
		MISC_G = 'misc_g',
		MISC_H = 'misc_h',
		MISC_I = 'misc_i',
		MISC_J = 'misc_j',
		MISC_K = 'misc_k',
		MISC_L = 'misc_l',
		MISC_M = 'misc_m',
		MISC_N = 'misc_n',
		MISC_O = 'misc_o',
		MISC_P = 'misc_p',
		MISC_Q = 'misc_q',
		MISC_R = 'misc_r',
		MISC_S = 'misc_s',
		MISC_T = 'misc_t',
		MISC_U = 'misc_u',
		MISC_V = 'misc_v',
		MISC_W = 'misc_w',
		MISC_X = 'misc_x',
		MISC_Y = 'misc_y',
		MISC_Z = 'misc_z',
		MISC_1 = 'misc_1',
		MISC_2 = 'misc_2',
		WEAPON_1A = 'weapon_1a',
		WEAPON_1B = 'weapon_1b',
		WEAPON_1C = 'weapon_1c',
		WEAPON_1D = 'weapon_1d',
		WEAPON_1A_ROT = 'weapon_1a_rot',
		WEAPON_1B_ROT = 'weapon_1b_rot',
		WEAPON_1C_ROT = 'weapon_1c_rot',
		WEAPON_1D_ROT = 'weapon_1d_rot',
		WEAPON_2A = 'weapon_2a',
		WEAPON_2B = 'weapon_2b',
		WEAPON_2C = 'weapon_2c',
		WEAPON_2D = 'weapon_2d',
		WEAPON_2A_ROT = 'weapon_2a_rot',
		WEAPON_2B_ROT = 'weapon_2b_rot',
		WEAPON_2C_ROT = 'weapon_2c_rot',
		WEAPON_2D_ROT = 'weapon_2d_rot',
		WEAPON_3A = 'weapon_3a',
		WEAPON_3B = 'weapon_3b',
		WEAPON_3C = 'weapon_3c',
		WEAPON_3D = 'weapon_3d',
		WEAPON_3A_ROT = 'weapon_3a_rot',
		WEAPON_3B_ROT = 'weapon_3b_rot',
		WEAPON_3C_ROT = 'weapon_3c_rot',
		WEAPON_3D_ROT = 'weapon_3d_rot',
		WEAPON_4A = 'weapon_4a',
		WEAPON_4B = 'weapon_4b',
		WEAPON_4C = 'weapon_4c',
		WEAPON_4D = 'weapon_4d',
		WEAPON_4A_ROT = 'weapon_4a_rot',
		WEAPON_4B_ROT = 'weapon_4b_rot',
		WEAPON_4C_ROT = 'weapon_4c_rot',
		WEAPON_4D_ROT = 'weapon_4d_rot',
		TURRET_1BASE = 'turret_1base',
		TURRET_1BARREL = 'turret_1barrel',
		TURRET_2BASE = 'turret_2base',
		TURRET_2BARREL = 'turret_2barrel',
		TURRET_3BASE = 'turret_3base',
		TURRET_3BARREL = 'turret_3barrel',
		AMMOBELT = 'ammobelt',
		SEARCHLIGHT_BASE = 'searchlight_base',
		SEARCHLIGHT_LIGHT = 'searchlight_light',
		ATTACH_FEMALE = 'attach_female',
		ROOF = 'roof',
		ROOF2 = 'roof2',
		SOFT_1 = 'soft_1',
		SOFT_2 = 'soft_2',
		SOFT_3 = 'soft_3',
		SOFT_4 = 'soft_4',
		SOFT_5 = 'soft_5',
		SOFT_6 = 'soft_6',
		SOFT_7 = 'soft_7',
		SOFT_8 = 'soft_8',
		SOFT_9 = 'soft_9',
		SOFT_10 = 'soft_10',
		SOFT_11 = 'soft_11',
		SOFT_12 = 'soft_12',
		SOFT_13 = 'soft_13',
		FORKS = 'forks',
		MAST = 'mast',
		CARRIAGE = 'carriage',
		FORK_L = 'fork_l',
		FORK_R = 'fork_r',
		FORKS_ATTACH = 'forks_attach',
		FRAME_1 = 'frame_1',
		FRAME_2 = 'frame_2',
		FRAME_3 = 'frame_3',
		FRAME_PICKUP_1 = 'frame_pickup_1',
		FRAME_PICKUP_2 = 'frame_pickup_2',
		FRAME_PICKUP_3 = 'frame_pickup_3',
		FRAME_PICKUP_4 = 'frame_pickup_4',
		FREIGHT_CONT = 'freight_cont',
		FREIGHT_BOGEY = 'freight_bogey',
		FREIGHTGRAIN_SLIDEDOOR = 'freightgrain_slidedoor',
		DOOR_HATCH_R = 'door_hatch_r',
		DOOR_HATCH_L = 'door_hatch_l',
		TOW_ARM = 'tow_arm',
		TOW_MOUNT_A = 'tow_mount_a',
		TOW_MOUNT_B = 'tow_mount_b',
		TIPPER = 'tipper',
		COMBINE_REEL = 'combine_reel',
		COMBINE_AUGER = 'combine_auger',
		SLIPSTREAM_L = 'slipstream_l',
		SLIPSTREAM_R = 'slipstream_r',
		ARM_1 = 'arm_1',
		ARM_2 = 'arm_2',
		ARM_3 = 'arm_3',
		ARM_4 = 'arm_4',
		SCOOP = 'scoop',
		BOOM = 'boom',
		STICK = 'stick',
		BUCKET = 'bucket',
		SHOVEL_2 = 'shovel_2',
		SHOVEL_3 = 'shovel_3',
		LOOKAT_UPPRPISTON_HEAD = 'Lookat_UpprPiston_head',
		LOOKAT_LOWRPISTON_BOOM = 'Lookat_LowrPiston_boom',
		BOOM_DRIVER = 'Boom_Driver',
		CUTTER_DRIVER = 'cutter_driver',
		VEHICLE_BLOCKER = 'vehicle_blocker',
		EXTRA_1 = 'extra_1',
		EXTRA_2 = 'extra_2',
		EXTRA_3 = 'extra_3',
		EXTRA_4 = 'extra_4',
		EXTRA_5 = 'extra_5',
		EXTRA_6 = 'extra_6',
		EXTRA_7 = 'extra_7',
		EXTRA_8 = 'extra_8',
		EXTRA_9 = 'extra_9',
		EXTRA_TEN = 'extra_ten',
		EXTRA_11 = 'extra_11',
		EXTRA_12 = 'extra_12',
		BREAK_EXTRA_1 = 'break_extra_1',
		BREAK_EXTRA_2 = 'break_extra_2',
		BREAK_EXTRA_3 = 'break_extra_3',
		BREAK_EXTRA_4 = 'break_extra_4',
		BREAK_EXTRA_5 = 'break_extra_5',
		BREAK_EXTRA_6 = 'break_extra_6',
		BREAK_EXTRA_7 = 'break_extra_7',
		BREAK_EXTRA_8 = 'break_extra_8',
		BREAK_EXTRA_9 = 'break_extra_9',
		BREAK_EXTRA_10 = 'break_extra_10',
		MOD_COL_1 = 'mod_col_1',
		MOD_COL_2 = 'mod_col_2',
		MOD_COL_3 = 'mod_col_3',
		MOD_COL_4 = 'mod_col_4',
		MOD_COL_5 = 'mod_col_5',
		HANDLEBARS = 'handlebars',
		FORKS_U = 'forks_u',
		FORKS_L = 'forks_l',
		WHEEL_F = 'wheel_f',
		SWINGARM = 'swingarm',
		WHEEL_R = 'wheel_r',
		CRANK = 'crank',
		PEDAL_R = 'pedal_r',
		PEDAL_L = 'pedal_l',
		STATIC_PROP = 'static_prop',
		MOVING_PROP = 'moving_prop',
		STATIC_PROP2 = 'static_prop2',
		MOVING_PROP2 = 'moving_prop2',
		RUDDER = 'rudder',
		RUDDER2 = 'rudder2',
		WHEEL_RF1_DUMMY = 'wheel_rf1_dummy',
		WHEEL_RF2_DUMMY = 'wheel_rf2_dummy',
		WHEEL_RF3_DUMMY = 'wheel_rf3_dummy',
		WHEEL_RB1_DUMMY = 'wheel_rb1_dummy',
		WHEEL_RB2_DUMMY = 'wheel_rb2_dummy',
		WHEEL_RB3_DUMMY = 'wheel_rb3_dummy',
		WHEEL_LF1_DUMMY = 'wheel_lf1_dummy',
		WHEEL_LF2_DUMMY = 'wheel_lf2_dummy',
		WHEEL_LF3_DUMMY = 'wheel_lf3_dummy',
		WHEEL_LB1_DUMMY = 'wheel_lb1_dummy',
		WHEEL_LB2_DUMMY = 'wheel_lb2_dummy',
		WHEEL_LB3_DUMMY = 'wheel_lb3_dummy',
		BOGIE_FRONT = 'bogie_front',
		BOGIE_REAR = 'bogie_rear',
		ROTOR_MAIN = 'rotor_main',
		ROTOR_REAR = 'rotor_rear',
		ROTOR_MAIN_2 = 'rotor_main_2',
		ROTOR_REAR_2 = 'rotor_rear_2',
		ELEVATORS = 'elevators',
		TAIL = 'tail',
		OUTRIGGERS_L = 'outriggers_l',
		OUTRIGGERS_R = 'outriggers_r',
		ROPE_ATTACH_A = 'rope_attach_a',
		ROPE_ATTACH_B = 'rope_attach_b',
		PROP_1 = 'prop_1',
		PROP_2 = 'prop_2',
		ELEVATOR_L = 'elevator_l',
		ELEVATOR_R = 'elevator_r',
		RUDDER_L = 'rudder_l',
		RUDDER_R = 'rudder_r',
		PROP_3 = 'prop_3',
		PROP_4 = 'prop_4',
		PROP_5 = 'prop_5',
		PROP_6 = 'prop_6',
		PROP_7 = 'prop_7',
		PROP_8 = 'prop_8',
		RUDDER_2 = 'rudder_2',
		AILERON_L = 'aileron_l',
		AILERON_R = 'aileron_r',
		AIRBRAKE_L = 'airbrake_l',
		AIRBRAKE_R = 'airbrake_r',
		WING_L = 'wing_l',
		WING_R = 'wing_r',
		WING_LR = 'wing_lr',
		WING_RR = 'wing_rr',
		ENGINE_L = 'engine_l',
		ENGINE_R = 'engine_r',
		NOZZLES_F = 'nozzles_f',
		NOZZLES_R = 'nozzles_r',
		AFTERBURNER = 'afterburner',
		WINGTIP_1 = 'wingtip_1',
		WINGTIP_2 = 'wingtip_2',
		GEAR_DOOR_FL = 'gear_door_fl',
		GEAR_DOOR_FR = 'gear_door_fr',
		GEAR_DOOR_RL1 = 'gear_door_rl1',
		GEAR_DOOR_RR1 = 'gear_door_rr1',
		GEAR_DOOR_RL2 = 'gear_door_rl2',
		GEAR_DOOR_RR2 = 'gear_door_rr2',
		GEAR_DOOR_RML = 'gear_door_rml',
		GEAR_DOOR_RMR = 'gear_door_rmr',
		GEAR_F = 'gear_f',
		GEAR_RL = 'gear_rl',
		GEAR_LM1 = 'gear_lm1',
		GEAR_RR = 'gear_rr',
		GEAR_RM1 = 'gear_rm1',
		GEAR_RM = 'gear_rm',
		PROP_LEFT = 'prop_left',
		PROP_RIGHT = 'prop_right',
		LEGS = 'legs',
		ATTACH_MALE = 'attach_male',
		DRAFT_ANIMAL_ATTACH_LR = 'draft_animal_attach_lr',
		DRAFT_ANIMAL_ATTACH_RR = 'draft_animal_attach_rr',
		DRAFT_ANIMAL_ATTACH_LM = 'draft_animal_attach_lm',
		DRAFT_ANIMAL_ATTACH_RM = 'draft_animal_attach_rm',
		DRAFT_ANIMAL_ATTACH_LF = 'draft_animal_attach_lf',
		DRAFT_ANIMAL_ATTACH_RF = 'draft_animal_attach_rf',
		WHEELCOVER_L = 'wheelcover_l',
		WHEELCOVER_R = 'wheelcover_r',
		BARRACKS = 'barracks',
		PONTOON_L = 'pontoon_l',
		PONTOON_R = 'pontoon_r',
		NO_PED_COL_STEP_L = 'no_ped_col_step_l',
		NO_PED_COL_STRUT_1_L = 'no_ped_col_strut_1_l',
		NO_PED_COL_STRUT_2_L = 'no_ped_col_strut_2_l',
		NO_PED_COL_STEP_R = 'no_ped_col_step_r',
		NO_PED_COL_STRUT_1_R = 'no_ped_col_strut_1_r',
		NO_PED_COL_STRUT_2_R = 'no_ped_col_strut_2_r',
		LIGHT_COVER = 'light_cover',
		EMISSIVES = 'emissives',
		NEON_L = 'neon_l',
		NEON_R = 'neon_r',
		NEON_F = 'neon_f',
		NEON_B = 'neon_b',
		DASHGLOW = 'dashglow',
		DOORLIGHT_LF = 'doorlight_lf',
		DOORLIGHT_RF = 'doorlight_rf',
		DOORLIGHT_LR = 'doorlight_lr',
		DOORLIGHT_RR = 'doorlight_rr',
		UNKNOWN_ID = 'unknown_id',
		DIALS = 'dials',
		ENGINEBLOCK = 'engineblock',
		BOBBLE_HEAD = 'bobble_head',
		BOBBLE_BASE = 'bobble_base',
		BOBBLE_HAND = 'bobble_hand',
		CHASSIS_CONTROL = 'chassis_Control',
	}

	/** [https://wiki.rage.mp/index.php?title=Vehicle_Classes](https://wiki.rage.mp/index.php?title=Vehicle_Classes) */
	const enum Classes {
		COMPACTS,
		SEDANS,
		SUVS,
		COUPES,
		MUSCLE,
		SPORTS_CLASSIC,
		SPORTS,
		SUPER,
		MOTORCYCLES,
		OFF_ROAD,
		INDUSTRIAl,
		UTILITY,
		VANS,
		CYCLES,
		BOATS,
		HELICOPTERS,
		PLANES,
		SERVICE,
		EMERGENCY,
		MILITARY,
		COMMERCIAl,
		TRAINS,
		OPEN_WHEEL,
	}
	
	/** [https://wiki.rage.mp/index.php?title=Vehicle_Flags](https://wiki.rage.mp/index.php?title=Vehicle_Flags) */
	const enum Flags {
		PRESSINGHORN = 1,
		SHOOTING = 2,
		SIRENACTIVE = 4,
		VEHICLEDEAD = 8,
		AIMING = 16,
		DRIVER = 32,
		HASAIMDATA = 64,
		BURNOUT = 128,
		EXITINGFVEHICLE = 256,
		PLAYERDEAD = 512
	}
	
	namespace Mod {
		/** [https://wiki.rage.mp/index.php?title=Vehicle_Mods](https://wiki.rage.mp/index.php?title=Vehicle_Mods) */
		const enum Types {
			SPOILERS = 0,
			FRONT_BUMPER = 1,
			REAR_BUMPER = 2,
			SIDE_SKIRT = 3,
			EXHAUST = 4,
			FRAME = 5,
			GRILLE = 6,
			HOOD = 7,
			FENDER = 8,
			RIGHT_FENDER = 9,
			ROOF = 10,
			ENGINE = 11,
			BRAKES = 12,
			TRANSMISSION = 13,
			/** 0 to 51 */
			HORNS = 14,
			SUSPENSION = 15,
			ARMOR = 16,
			TURBO = 18,
			XENON = 22,
			FRONT_WHEELS = 23,
			UTIL_SHADOW_SILVER = 20,
			/** Only for Motorcycles */
			BACK_WHEELS = 24,
			PLATE_HOLDERS = 25,
			TRIM_DESIGN = 27,
			ORNAMENTS = 28,
			DIAL_DESIGN = 30,
			STEERING_WHEEL = 33,
			SHIFT_LEVER = 34,
			PLAQUES = 35,
			HYDRAULICS = 38,
			BOOST = 40,
			WINDOW_TINT = 55,
			LIVERY = 48,
			PLATE = 62,
			/** 0 to 74 */
			COLOUR_1 = 66,
			/** 0 to 74 */
			COLOUR_2 = 67,
		}
	}
	
	namespace Color {
		/** [https://wiki.rage.mp/index.php?title=Vehicle_Colors](https://wiki.rage.mp/index.php?title=Vehicle_Colors) */
		const enum Hash {
			/** ![#0d1116](https://htmlcolors.com/color-image/0d1116.png) */
			METALLIC_BLACK = "#0d1116",
			/** ![#1c1d21](https://htmlcolors.com/color-image/1c1d21.png) */
			METALLIC_GRAPHITE_BLACK = "#1c1d21",
			/** ![#32383d](https://htmlcolors.com/color-image/32383d.png) */
			METALLIC_BLACK_STEAL = "#32383d",
			/** ![#454b4f](https://htmlcolors.com/color-image/454b4f.png) */
			METALLIC_DARK_SILVER = "#454b4f",
			/** ![#999da0](https://htmlcolors.com/color-image/999da0.png) */
			METALLIC_SILVER = "#999da0",
			/** ![#c2c4c6](https://htmlcolors.com/color-image/c2c4c6.png) */
			METALLIC_BLUE_SILVER = "#c2c4c6",
			/** ![#979a97](https://htmlcolors.com/color-image/979a97.png) */
			METALLIC_STEEL_GRAY = "#979a97",
			/** ![#637380](https://htmlcolors.com/color-image/637380.png) */
			METALLIC_SHADOW_SILVER = "#637380",
			/** ![#63625c](https://htmlcolors.com/color-image/63625c.png) */
			METALLIC_STONE_SILVER = "#63625c",
			/** ![#3c3f47](https://htmlcolors.com/color-image/3c3f47.png) */
			METALLIC_MIDNIGHT_SILVER = "#3c3f47",
			/** ![#444e54](https://htmlcolors.com/color-image/444e54.png) */
			METALLIC_GUN_METAL = "#444e54",
			/** ![#1d2129](https://htmlcolors.com/color-image/1d2129.png) */
			METALLIC_ANTHRACITE_GREY = "#1d2129",
			/** ![#13181f](https://htmlcolors.com/color-image/13181f.png) */
			MATTE_BLACK = "#13181f",
			/** ![#26282a](https://htmlcolors.com/color-image/26282a.png) */
			MATTE_GRAY = "#26282a",
			/** ![#515554](https://htmlcolors.com/color-image/515554.png) */
			MATTE_LIGHT_GREY = "#515554",
			/** ![#151921](https://htmlcolors.com/color-image/151921.png) */
			UTIL_BLACK = "#151921",
			/** ![#1e2429](https://htmlcolors.com/color-image/1e2429.png) */
			UTIL_BLACK_POLY = "#1e2429",
			/** ![#333a3c](https://htmlcolors.com/color-image/333a3c.png) */
			UTIL_DARK_SILVER = "#333a3c",
			/** ![#8c9095](https://htmlcolors.com/color-image/8c9095.png) */
			UTIL_SILVER = "#8c9095",
			/** ![#39434d](https://htmlcolors.com/color-image/39434d.png) */
			UTIL_GUN_METAL = "#39434d",
			/** ![#506272](https://htmlcolors.com/color-image/506272.png) */
			UTIL_SHADOW_SILVER = "#506272",
			/** ![#1e232f](https://htmlcolors.com/color-image/1e232f.png) */
			WORN_BLACK = "#1e232f",
			/** ![#363a3f](https://htmlcolors.com/color-image/363a3f.png) */
			WORN_GRAPHITE = "#363a3f",
			/** ![#a0a199](https://htmlcolors.com/color-image/a0a199.png) */
			WORN_SILVER_GREY = "#a0a199",
			/** ![#d3d3d3](https://htmlcolors.com/color-image/d3d3d3.png) */
			WORN_SILVER = "#d3d3d3",
			/** ![#b7bfca](https://htmlcolors.com/color-image/b7bfca.png) */
			WORN_BLUE_SILVER = "#b7bfca",
			/** ![#778794](https://htmlcolors.com/color-image/778794.png) */
			WORN_SHADOW_SILVER = "#778794",
			/** ![#c00e1a](https://htmlcolors.com/color-image/c00e1a.png) */
			METALLIC_RED = "#c00e1a",
			/** ![#da1918](https://htmlcolors.com/color-image/da1918.png) */
			METALLIC_TORINO_RED = "#da1918",
			/** ![#b6111b](https://htmlcolors.com/color-image/b6111b.png) */
			METALLIC_FORMULA_RED = "#b6111b",
			/** ![#a51e23](https://htmlcolors.com/color-image/a51e23.png) */
			METALLIC_BLAZE_RED = "#a51e23",
			/** ![#7b1a22](https://htmlcolors.com/color-image/7b1a22.png) */
			METALLIC_GRACEFUL_RED = "#7b1a22",
			/** ![#8e1b1f](https://htmlcolors.com/color-image/8e1b1f.png) */
			METALLIC_GARNET_RED = "#8e1b1f",
			/** ![#6f1818](https://htmlcolors.com/color-image/6f1818.png) */
			METALLIC_DESERT_RED = "#6f1818",
			/** ![#49111d](https://htmlcolors.com/color-image/49111d.png) */
			METALLIC_CABERNET_RED = "#49111d",
			/** ![#b60f25](https://htmlcolors.com/color-image/b60f25.png) */
			METALLIC_CANDY_RED = "#b60f25",
			/** ![#d44a17](https://htmlcolors.com/color-image/d44a17.png) */
			METALLIC_SUNRISE_ORANGE = "#d44a17",
			/** ![#c2944f](https://htmlcolors.com/color-image/c2944f.png) */
			METALLIC_CLASSIC_GOLD = "#c2944f",
			/** ![#f78616](https://htmlcolors.com/color-image/f78616.png) */
			METALLIC_ORANGE = "#f78616",
			/** ![#cf1f21](https://htmlcolors.com/color-image/cf1f21.png) */
			MATTE_RED = "#cf1f21",
			/** ![#732021](https://htmlcolors.com/color-image/732021.png) */
			MATTE_DARK_RED = "#732021",
			/** ![#f27d20](https://htmlcolors.com/color-image/f27d20.png) */
			MATTE_ORANGE = "#f27d20",
			/** ![#ffc91f](https://htmlcolors.com/color-image/ffc91f.png) */
			MATTE_YELLOW = "#ffc91f",
			/** ![#9c1016](https://htmlcolors.com/color-image/9c1016.png) */
			UTIL_RED = "#9c1016",
			/** ![#de0f18](https://htmlcolors.com/color-image/de0f18.png) */
			UTIL_BRIGHT_RED = "#de0f18",
			/** ![#8f1e17](https://htmlcolors.com/color-image/8f1e17.png) */
			UTIL_GARNET_RED = "#8f1e17",
			/** ![#a94744](https://htmlcolors.com/color-image/a94744.png) */
			WORN_RED = "#a94744",
			/** ![#b16c51](https://htmlcolors.com/color-image/b16c51.png) */
			WORN_GOLDEN_RED = "#b16c51",
			/** ![#371c25](https://htmlcolors.com/color-image/371c25.png) */
			WORN_DARK_RED = "#371c25",
			/** ![#132428](https://htmlcolors.com/color-image/132428.png) */
			METALLIC_DARK_GREEN = "#132428",
			/** ![#122e2b](https://htmlcolors.com/color-image/122e2b.png) */
			METALLIC_RACING_GREEN = "#122e2b",
			/** ![#12383c](https://htmlcolors.com/color-image/12383c.png) */
			METALLIC_SEA_GREEN = "#12383c",
			/** ![#31423f](https://htmlcolors.com/color-image/31423f.png) */
			METALLIC_OLIVE_GREEN = "#31423f",
			/** ![#155c2d](https://htmlcolors.com/color-image/155c2d.png) */
			METALLIC_GREEN = "#155c2d",
			/** ![#1b6770](https://htmlcolors.com/color-image/1b6770.png) */
			METALLIC_GASOLINE_BLUE_GREEN = "#1b6770",
			/** ![#66b81f](https://htmlcolors.com/color-image/66b81f.png) */
			MATTE_LIME_GREEN = "#66b81f",
			/** ![#22383e](https://htmlcolors.com/color-image/22383e.png) */
			UTIL_DARK_GREEN = "#22383e",
			/** ![#1d5a3f](https://htmlcolors.com/color-image/1d5a3f.png) */
			UTIL_GREEN = "#1d5a3f",
			/** ![#2d423f](https://htmlcolors.com/color-image/2d423f.png) */
			WORN_DARK_GREEN = "#2d423f",
			/** ![#45594b](https://htmlcolors.com/color-image/45594b.png) */
			WORN_GREEN = "#45594b",
			/** ![#65867f](https://htmlcolors.com/color-image/65867f.png) */
			WORN_SEA_WASH = "#65867f",
			/** ![#222e46](https://htmlcolors.com/color-image/222e46.png) */
			METALLIC_MIDNIGHT_BLUE = "#222e46",
			/** ![#233155](https://htmlcolors.com/color-image/233155.png) */
			METALLIC_DARK_BLUE = "#233155",
			/** ![#304c7e](https://htmlcolors.com/color-image/304c7e.png) */
			METALLIC_SAXONY_BLUE = "#304c7e",
			/** ![#47578f](https://htmlcolors.com/color-image/47578f.png) */
			METALLIC_BLUE = "#47578f",
			/** ![#637ba7](https://htmlcolors.com/color-image/637ba7.png) */
			METALLIC_MARINER_BLUE = "#637ba7",
			/** ![#394762](https://htmlcolors.com/color-image/394762.png) */
			METALLIC_HARBOR_BLUE = "#394762",
			/** ![#d6e7f1](https://htmlcolors.com/color-image/d6e7f1.png) */
			METALLIC_DIAMOND_BLUE = "#d6e7f1",
			/** ![#76afbe](https://htmlcolors.com/color-image/76afbe.png) */
			METALLIC_SURF_BLUE = "#76afbe",
			/** ![#345e72](https://htmlcolors.com/color-image/345e72.png) */
			METALLIC_NAUTICAL_BLUE = "#345e72",
			/** ![#0b9cf1](https://htmlcolors.com/color-image/0b9cf1.png) */
			METALLIC_BRIGHT_BLUE = "#0b9cf1",
			/** ![#2f2d52](https://htmlcolors.com/color-image/2f2d52.png) */
			METALLIC_PURPLE_BLUE = "#2f2d52",
			/** ![#282c4d](https://htmlcolors.com/color-image/282c4d.png) */
			METALLIC_SPINNAKER_BLUE = "#282c4d",
			/** ![#2354a1](https://htmlcolors.com/color-image/2354a1.png) */
			METALLIC_ULTRA_BLUE = "#2354a1",
			/** ![#6ea3c6](https://htmlcolors.com/color-image/6ea3c6.png) */
			METALLIC_BRIGHT_BLUE_2 = "#6ea3c6",
			/** ![#112552](https://htmlcolors.com/color-image/112552.png) */
			UTIL_DARK_BLUE = "#112552",
			/** ![#1b203e](https://htmlcolors.com/color-image/1b203e.png) */
			UTIL_MIDNIGHT_BLUE = "#1b203e",
			/** ![#275190](https://htmlcolors.com/color-image/275190.png) */
			UTIL_BLUE = "#275190",
			/** ![#608592](https://htmlcolors.com/color-image/608592.png) */
			UTIL_SEA_FOAM_BLUE = "#608592",
			/** ![#2446a8](https://htmlcolors.com/color-image/2446a8.png) */
			UTIL_LIGHTNING_BLUE = "#2446a8",
			/** ![#4271e1](https://htmlcolors.com/color-image/4271e1.png) */
			UTIL_MAUI_BLUE_POLY = "#4271e1",
			/** ![#3b39e0](https://htmlcolors.com/color-image/3b39e0.png) */
			UTIL_BRIGHT_BLUE = "#3b39e0",
			/** ![#1f2852](https://htmlcolors.com/color-image/1f2852.png) */
			MATTE_DARK_BLUE = "#1f2852",
			/** ![#253aa7](https://htmlcolors.com/color-image/253aa7.png) */
			MATTE_BLUE = "#253aa7",
			/** ![#1c3551](https://htmlcolors.com/color-image/1c3551.png) */
			MATTE_MIDNIGHT_BLUE = "#1c3551",
			/** ![#4c5f81](https://htmlcolors.com/color-image/4c5f81.png) */
			WORN_DARK_BLUE = "#4c5f81",
			/** ![#58688e](https://htmlcolors.com/color-image/58688e.png) */
			WORN_BLUE = "#58688e",
			/** ![#74b5d8](https://htmlcolors.com/color-image/74b5d8.png) */
			WORN_LIGHT_BLUE = "#74b5d8",
			/** ![#ffcf20](https://htmlcolors.com/color-image/ffcf20.png) */
			METALLIC_TAXI_YELLOW = "#ffcf20",
			/** ![#fbe212](https://htmlcolors.com/color-image/fbe212.png) */
			METALLIC_RACE_YELLOW = "#fbe212",
			/** ![#916532](https://htmlcolors.com/color-image/916532.png) */
			METALLIC_BRONZE = "#916532",
			/** ![#e0e13d](https://htmlcolors.com/color-image/e0e13d.png) */
			METALLIC_YELLOW_BIRD = "#e0e13d",
			/** ![#98d223](https://htmlcolors.com/color-image/98d223.png) */
			METALLIC_LIME = "#98d223",
			/** ![#9b8c78](https://htmlcolors.com/color-image/9b8c78.png) */
			METALLIC_CHAMPAGNE = "#9b8c78",
			/** ![#503218](https://htmlcolors.com/color-image/503218.png) */
			METALLIC_PUEBLO_BEIGE = "#503218",
			/** ![#473f2b](https://htmlcolors.com/color-image/473f2b.png) */
			METALLIC_DARK_IVORY = "#473f2b",
			/** ![#221b19](https://htmlcolors.com/color-image/221b19.png) */
			METALLIC_CHOCO_BROWN = "#221b19",
			/** ![#653f23](https://htmlcolors.com/color-image/653f23.png) */
			METALLIC_GOLDEN_BROWN = "#653f23",
			/** ![#775c3e](https://htmlcolors.com/color-image/775c3e.png) */
			METALLIC_LIGHT_BROWN = "#775c3e",
			/** ![#ac9975](https://htmlcolors.com/color-image/ac9975.png) */
			METALLIC_STRAW_BEIGE = "#ac9975",
			/** ![#6c6b4b](https://htmlcolors.com/color-image/6c6b4b.png) */
			METALLIC_MOSS_BROWN = "#6c6b4b",
			/** ![#402e2b](https://htmlcolors.com/color-image/402e2b.png) */
			METALLIC_BISTON_BROWN = "#402e2b",
			/** ![#a4965f](https://htmlcolors.com/color-image/a4965f.png) */
			METALLIC_BEECHWOOD = "#a4965f",
			/** ![#46231a](https://htmlcolors.com/color-image/46231a.png) */
			METALLIC_DARK_BEECHWOOD = "#46231a",
			/** ![#752b19](https://htmlcolors.com/color-image/752b19.png) */
			METALLIC_CHOCO_ORANGE = "#752b19",
			/** ![#bfae7b](https://htmlcolors.com/color-image/bfae7b.png) */
			METALLIC_BEACH_SAND = "#bfae7b",
			/** ![#dfd5b2](https://htmlcolors.com/color-image/dfd5b2.png) */
			METALLIC_SUN_BLEECHED_SAND = "#dfd5b2",
			/** ![#f7edd5](https://htmlcolors.com/color-image/f7edd5.png) */
			METALLIC_CREAM = "#f7edd5",
			/** ![#3a2a1b](https://htmlcolors.com/color-image/3a2a1b.png) */
			UTIL_BROWN = "#3a2a1b",
			/** ![#785f33](https://htmlcolors.com/color-image/785f33.png) */
			UTIL_MEDIUM_BROWN = "#785f33",
			/** ![#b5a079](https://htmlcolors.com/color-image/b5a079.png) */
			UTIL_LIGHT_BROWN = "#b5a079",
			/** ![#fffff6](https://htmlcolors.com/color-image/fffff6.png) */
			METALLIC_WHITE = "#fffff6",
			/** ![#eaeaea](https://htmlcolors.com/color-image/eaeaea.png) */
			METALLIC_FROST_WHITE = "#eaeaea",
			/** ![#b0ab94](https://htmlcolors.com/color-image/b0ab94.png) */
			WORN_HONEY_BEIGE = "#b0ab94",
			/** ![#453831](https://htmlcolors.com/color-image/453831.png) */
			WORN_BROWN = "#453831",
			/** ![#2a282b](https://htmlcolors.com/color-image/2a282b.png) */
			WORN_DARK_BROWN = "#2a282b",
			/** ![#726c57](https://htmlcolors.com/color-image/726c57.png) */
			WORN_STRAW_BEIGE = "#726c57",
			/** ![#6a747c](https://htmlcolors.com/color-image/6a747c.png) */
			BRUSHED_STEEL = "#6a747c",
			/** ![#354158](https://htmlcolors.com/color-image/354158.png) */
			BRUSHED_BLACK_STEEL = "#354158",
			/** ![#9ba0a8](https://htmlcolors.com/color-image/9ba0a8.png) */
			BRUSHED_ALUMINIUM = "#9ba0a8",
			/** ![#5870a1](https://htmlcolors.com/color-image/5870a1.png) */
			CHROME = "#5870a1",
			/** ![#eae6de](https://htmlcolors.com/color-image/eae6de.png) */
			WORN_OFF_WHITE = "#eae6de",
			/** ![#dfddd0](https://htmlcolors.com/color-image/dfddd0.png) */
			UTIL_OFF_WHITE = "#dfddd0",
			/** ![#f2ad2e](https://htmlcolors.com/color-image/f2ad2e.png) */
			WORN_ORANGE = "#f2ad2e",
			/** ![#f9a458](https://htmlcolors.com/color-image/f9a458.png) */
			WORN_LIGHT_ORANGE = "#f9a458",
			/** ![#83c566](https://htmlcolors.com/color-image/83c566.png) */
			METALLIC_SECURICOR_GREEN = "#83c566",
			/** ![#f1cc40](https://htmlcolors.com/color-image/f1cc40.png) */
			WORN_TAXI_YELLOW = "#f1cc40",
			/** ![#4cc3da](https://htmlcolors.com/color-image/4cc3da.png) */
			POLICE_CAR_BLUE = "#4cc3da",
			/** ![#4e6443](https://htmlcolors.com/color-image/4e6443.png) */
			MATTE_GREEN = "#4e6443",
			/** ![#bcac8f](https://htmlcolors.com/color-image/bcac8f.png) */
			MATTE_BROWN = "#bcac8f",
			/** ![#f8b658](https://htmlcolors.com/color-image/f8b658.png) */
			WORN_ORANGE_2 = "#f8b658",
			/** ![#fcf9f1](https://htmlcolors.com/color-image/fcf9f1.png) */
			MATTE_WHITE = "#fcf9f1",
			/** ![#fffffb](https://htmlcolors.com/color-image/fffffb.png) */
			WORN_WHITE = "#fffffb",
			/** ![#81844c](https://htmlcolors.com/color-image/81844c.png) */
			WORN_OLIVE_ARMY_GREEN = "#81844c",
			/** ![#ffffff](https://htmlcolors.com/color-image/ffffff.png) */
			PURE_WHITE = "#ffffff",
			/** ![#f21f99](https://htmlcolors.com/color-image/f21f99.png) */
			HOT_PINK = "#f21f99",
			/** ![#fdd6cd](https://htmlcolors.com/color-image/fdd6cd.png) */
			SALMON_PINK = "#fdd6cd",
			/** ![#df5891](https://htmlcolors.com/color-image/df5891.png) */
			METALLIC_VERMILLION_PINK = "#df5891",
			/** ![#f6ae20](https://htmlcolors.com/color-image/f6ae20.png) */
			ORANGE = "#f6ae20",
			/** ![#b0ee6e](https://htmlcolors.com/color-image/b0ee6e.png) */
			GREEN = "#b0ee6e",
			/** ![#08e9fa](https://htmlcolors.com/color-image/08e9fa.png) */
			BLUE = "#08e9fa",
			/** ![#0a0c17](https://htmlcolors.com/color-image/0a0c17.png) */
			METTALIC_BLACK_BLUE = "#0a0c17",
			/** ![#0c0d18](https://htmlcolors.com/color-image/0c0d18.png) */
			METALLIC_BLACK_PURPLE = "#0c0d18",
			/** ![#0e0d14](https://htmlcolors.com/color-image/0e0d14.png) */
			METALLIC_BLACK_RED = "#0e0d14",
			/** ![#9f9e8a](https://htmlcolors.com/color-image/9f9e8a.png) */
			HUNTER_GREEN = "#9f9e8a",
			/** ![#621276](https://htmlcolors.com/color-image/621276.png) */
			METALLIC_PURPLE = "#621276",
			/** ![#0b1421](https://htmlcolors.com/color-image/0b1421.png) */
			METAILLIC_V_DARK_BLUE = "#0b1421",
			/** ![#11141a](https://htmlcolors.com/color-image/11141a.png) */
			MODSHOP_BLACK1 = "#11141a",
			/** ![#6b1f7b](https://htmlcolors.com/color-image/6b1f7b.png) */
			MATTE_PURPLE = "#6b1f7b",
			/** ![#1e1d22](https://htmlcolors.com/color-image/1e1d22.png) */
			MATTE_DARK_PURPLE = "#1e1d22",
			/** ![#bc1917](https://htmlcolors.com/color-image/bc1917.png) */
			METALLIC_LAVA_RED = "#bc1917",
			/** ![#2d362a](https://htmlcolors.com/color-image/2d362a.png) */
			MATTE_FOREST_GREEN = "#2d362a",
			/** ![#696748](https://htmlcolors.com/color-image/696748.png) */
			MATTE_OLIVE_DRAB = "#696748",
			/** ![#7a6c55](https://htmlcolors.com/color-image/7a6c55.png) */
			MATTE_DESERT_BROWN = "#7a6c55",
			/** ![#c3b492](https://htmlcolors.com/color-image/c3b492.png) */
			MATTE_DESERT_TAN = "#c3b492",
			/** ![#5a6352](https://htmlcolors.com/color-image/5a6352.png) */
			MATTE_FOILAGE_GREEN = "#5a6352",
			/** ![#81827f](https://htmlcolors.com/color-image/81827f.png) */
			DEFAULT_ALLOY_COLOR = "#81827f",
			/** ![#afd6e4](https://htmlcolors.com/color-image/afd6e4.png) */
			EPSILON_BLUE = "#afd6e4",
			/** ![#7a6440](https://htmlcolors.com/color-image/7a6440.png) */
			PURE_GOLD = "#7a6440",
			/** ![#7f6a48](https://htmlcolors.com/color-image/7f6a48.png) */
			BRUSHED_GOLD = "#7f6a48",
		}
	}
}
