declare namespace RageEnums {
	/** [https://wiki.rage.mp/index.php?title=Weapons](https://wiki.rage.mp/index.php?title=Weapons) */
	namespace Weapons {
		const enum Key {
			/** ![AntiqueCavalryDagger](https://wiki.rage.mp//images/thumb/f/f5/Antique-cavalry-dagger-icon.png/164px-Antique-cavalry-dagger-icon.png) */
			DAGGER = "weapon_dagger",
			/** ![BaseballBat](https://wiki.rage.mp//images/thumb/8/8b/Baseball-bat-icon.png/164px-Baseball-bat-icon.png) */
			BAT = "weapon_bat",
			/** ![BrokenBottle](https://wiki.rage.mp//images/5/5b/Broken-bottle-icon.png) */
			BOTTLE = "weapon_bottle",
			/** ![Crowbar](https://wiki.rage.mp//images/thumb/8/8a/Crowbar-icon.png/164px-Crowbar-icon.png) */
			CROWBAR = "weapon_crowbar",
			/** ![Fist](https://wiki.rage.mp//images/b/b7/Fist-icon.png) */
			UNARMED = "weapon_unarmed",
			/** ![Flashlight](https://wiki.rage.mp//images/thumb/8/85/Flashlight-icon.png/164px-Flashlight-icon.png) */
			FLASHLIGHT = "weapon_flashlight",
			/** ![GolfClub](https://wiki.rage.mp//images/thumb/c/cb/Golf-club-icon.png/164px-Golf-club-icon.png) */
			GOLFCLUB = "weapon_golfclub",
			/** ![Hammer](https://wiki.rage.mp//images/thumb/e/ec/Hammer-icon.png/164px-Hammer-icon.png) */
			HAMMER = "weapon_hammer",
			/** ![Hatchet](https://wiki.rage.mp//images/thumb/e/eb/Hatchet-icon.png/164px-Hatchet-icon.png) */
			HATCHET = "weapon_hatchet",
			/** ![BrassKnuckles](https://wiki.rage.mp//images/b/b7/Knuckles-icon.png) */
			KNUCKLE = "weapon_knuckle",
			/** ![Knife](https://wiki.rage.mp//images/thumb/8/8c/Knife-icon.png/164px-Knife-icon.png) */
			KNIFE = "weapon_knife",
			/** ![Machete](https://wiki.rage.mp//images/thumb/d/dc/Machete-icon.png/164px-Machete-icon.png) */
			MACHETE = "weapon_machete",
			/** ![Switchblade](https://wiki.rage.mp//images/thumb/c/ce/Switch-blade-icon.png/164px-Switch-blade-icon.png) */
			SWITCHBLADE = "weapon_switchblade",
			/** ![Nightstick](https://wiki.rage.mp//images/thumb/e/e6/Nightstick-icon.png/164px-Nightstick-icon.png) */
			NIGHTSTICK = "weapon_nightstick",
			/** ![PipeWrench](https://wiki.rage.mp//images/thumb/2/22/Pipe-wrench-icon.png/164px-Pipe-wrench-icon.png) */
			WRENCH = "weapon_wrench",
			/** ![BattleAxe](https://wiki.rage.mp//images/thumb/3/3b/Battle-axe-icon.png/164px-Battle-axe-icon.png) */
			BATTLEAXE = "weapon_battleaxe",
			/** ![PoolCue](https://wiki.rage.mp//images/thumb/3/3a/Pool-cue-icon.png/164px-Pool-cue-icon.png) */
			POOLCUE = "weapon_poolcue",
			/** ![StoneHatchet](https://wiki.rage.mp//images/thumb/2/21/Stone-hatchet-icon.png/164px-Stone-hatchet-icon.png) */
			STONE_HATCHET = "weapon_stone_hatchet",
			/** ![Pistol](https://wiki.rage.mp//images/9/95/Pistol-icon.png) */
			PISTOL = "weapon_pistol",
			/** ![PistolMkII](https://wiki.rage.mp//images/4/43/Pistol-mk2-icon.png) */
			PISTOL_MK2 = "weapon_pistol_mk2",
			/** ![CombatPistol](https://wiki.rage.mp//images/1/16/Combat-pistol-icon.png) */
			COMBATPISTOL = "weapon_combatpistol",
			/** ![APPistol](https://wiki.rage.mp//images/4/4d/Appistol-icon.png) */
			APPISTOL = "weapon_appistol",
			/** ![StunGun](https://wiki.rage.mp//images/3/3c/Stungun-icon.png) */
			STUNGUN = "weapon_stungun",
			/** ![Pistol.50](https://wiki.rage.mp//images/c/c5/Pistol.50-icon.png) */
			PISTOL50 = "weapon_pistol50",
			/** ![SNSPistol](https://wiki.rage.mp//images/9/96/Sns-pistol-icon.png) */
			SNSPISTOL = "weapon_snspistol",
			/** ![SNSPistolMkII](https://wiki.rage.mp//images/1/16/Sns-pistol-mk2-icon.png) */
			SNSPISTOL_MK2 = "weapon_snspistol_mk2",
			/** ![HeavyPistol](https://wiki.rage.mp//images/7/78/Heavy-pistol-icon.png) */
			HEAVYPISTOL = "weapon_heavypistol",
			/** ![VintagePistol](https://wiki.rage.mp//images/9/97/Vintage-pistol-icon.png) */
			VINTAGEPISTOL = "weapon_vintagepistol",
			/** ![FlareGun](https://wiki.rage.mp//images/0/0d/Flaregun-icon.png) */
			FLAREGUN = "weapon_flaregun",
			/** ![MarksmanPistol](https://wiki.rage.mp//images/thumb/4/47/Marksman-pistol-icon.png/164px-Marksman-pistol-icon.png) */
			MARKSMANPISTOL = "weapon_marksmanpistol",
			/** ![HeavyRevolver](https://wiki.rage.mp//images/thumb/9/93/Heavy-revolver-icon.png/164px-Heavy-revolver-icon.png) */
			REVOLVER = "weapon_revolver",
			/** ![HeavyRevolverMkII](https://wiki.rage.mp//images/thumb/c/c0/Heavy-revolver-mk2-icon.png/164px-Heavy-revolver-mk2-icon.png) */
			REVOLVER_MK2 = "weapon_revolver_mk2",
			/** ![DoubleActionRevolver](https://wiki.rage.mp//images/thumb/4/45/Double-action-revolver-icon.png/164px-Double-action-revolver-icon.png) */
			DOUBLEACTION = "weapon_doubleaction",
			/** ![Up-n-Atomizer](https://wiki.rage.mp//images/thumb/8/89/Up-n-atomizer-icon.png/164px-Up-n-atomizer-icon.png) */
			RAYPISTOL = "weapon_raypistol",
			/** ![CeramicPistol](https://wiki.rage.mp//images/a/ad/Ceramic-pistol-icon.png) */
			CERAMICPISTOL = "weapon_ceramicpistol",
			/** ![NavyRevolver](https://wiki.rage.mp//images/thumb/1/15/Navy-revolver-icon.png/164px-Navy-revolver-icon.png) */
			NAVYREVOLVER = "weapon_navyrevolver",
			/** ![PericoPistol](https://wiki.rage.mp//images/thumb/3/31/Perico-pistol-icon.png/164px-Perico-pistol-icon.png) */
			GADGETPISTOL = "weapon_gadgetpistol",
			/** ![MicroSMG](https://wiki.rage.mp//images/thumb/3/3a/Micro-smg-icon.png/164px-Micro-smg-icon.png) */
			MICROSMG = "weapon_microsmg",
			/** ![SMG](https://wiki.rage.mp//images/thumb/3/30/Smg-icon.png/164px-Smg-icon.png) */
			SMG = "weapon_smg",
			/** ![SMGMkII](https://wiki.rage.mp//images/thumb/d/d1/Smg-mk2-icon.png/164px-Smg-mk2-icon.png) */
			SMG_MK2 = "weapon_smg_mk2",
			/** ![AssaultSMG](https://wiki.rage.mp//images/thumb/3/30/Assault-smg-icon.png/164px-Assault-smg-icon.png) */
			ASSAULTSMG = "weapon_assaultsmg",
			/** ![CombatPDW](https://wiki.rage.mp//images/thumb/4/45/Combat-pdw-icon.png/164px-Combat-pdw-icon.png) */
			COMBATPDW = "weapon_combatpdw",
			/** ![MachinePistol](https://wiki.rage.mp//images/thumb/2/24/Machine-pistol-icon.png/164px-Machine-pistol-icon.png) */
			MACHINEPISTOL = "weapon_machinepistol",
			/** ![MiniSMG](https://wiki.rage.mp//images/thumb/d/d3/Mini-smg-icon.png/164px-Mini-smg-icon.png) */
			MINISMG = "weapon_minismg",
			/** ![UnholyHellbringer](https://wiki.rage.mp//images/thumb/8/8f/Unholy-hellbringer-icon.png/164px-Unholy-hellbringer-icon.png) */
			RAYCARBINE = "weapon_raycarbine",
			/** ![PumpShotgun](https://wiki.rage.mp//images/thumb/0/09/Pump-shotgun-icon.png/164px-Pump-shotgun-icon.png) */
			PUMPSHOTGUN = "weapon_pumpshotgun",
			/** ![PumpShotgunMkII](https://wiki.rage.mp//images/thumb/6/69/Pump-shotgun-mk2-icon.png/164px-Pump-shotgun-mk2-icon.png) */
			PUMPSHOTGUN_MK2 = "weapon_pumpshotgun_mk2",
			/** ![Sawed-OffShotgun](https://wiki.rage.mp//images/thumb/b/ba/Sawed-off-shotgun-icon.png/164px-Sawed-off-shotgun-icon.png) */
			SAWNOFFSHOTGUN = "weapon_sawnoffshotgun",
			/** ![AssaultShotgun](https://wiki.rage.mp//images/thumb/e/e3/Assault-shotgun-icon.png/164px-Assault-shotgun-icon.png) */
			ASSAULTSHOTGUN = "weapon_assaultshotgun",
			/** ![BullpupShotgun](https://wiki.rage.mp//images/thumb/7/7f/Bullpup-shotgun-icon.png/164px-Bullpup-shotgun-icon.png) */
			BULLPUPSHOTGUN = "weapon_bullpupshotgun",
			/** ![Musket](https://wiki.rage.mp//images/thumb/8/8c/Musket-icon.png/164px-Musket-icon.png) */
			MUSKET = "weapon_musket",
			/** ![HeavyShotgun](https://wiki.rage.mp//images/thumb/5/5d/Heavy-shotgun-icon.png/164px-Heavy-shotgun-icon.png) */
			HEAVYSHOTGUN = "weapon_heavyshotgun",
			/** ![DoubleBarrelShotgun](https://wiki.rage.mp//images/thumb/8/8d/Double-barrel-shotgun-icon.png/164px-Double-barrel-shotgun-icon.png) */
			DBSHOTGUN = "weapon_dbshotgun",
			/** ![SweeperShotgun](https://wiki.rage.mp//images/thumb/a/a8/Sweeper-shotgun-icon.png/164px-Sweeper-shotgun-icon.png) */
			AUTOSHOTGUN = "weapon_autoshotgun",
			/** ![CombatShotgun](https://wiki.rage.mp//images/thumb/5/50/Combat-shotgun-icon.png/164px-Combat-shotgun-icon.png) */
			COMBATSHOTGUN = "weapon_combatshotgun",
			/** ![AssaultRifle](https://wiki.rage.mp//images/thumb/6/61/Assault-rifle-icon.png/164px-Assault-rifle-icon.png) */
			ASSAULTRIFLE = "weapon_assaultrifle",
			/** ![AssaultRifleMkII](https://wiki.rage.mp//images/thumb/6/63/Assault-rifle-mk2-icon.png/164px-Assault-rifle-mk2-icon.png) */
			ASSAULTRIFLE_MK2 = "weapon_assaultrifle_mk2",
			/** ![CarbineRifle](https://wiki.rage.mp//images/thumb/7/73/Carbine-rifle-icon.png/164px-Carbine-rifle-icon.png) */
			CARBINERIFLE = "weapon_carbinerifle",
			/** ![CarbineRifleMkII](https://wiki.rage.mp//images/thumb/3/3f/Carbine-rifle-mk2-icon.png/164px-Carbine-rifle-mk2-icon.png) */
			CARBINERIFLE_MK2 = "weapon_carbinerifle_mk2",
			/** ![AdvancedRifle](https://wiki.rage.mp//images/thumb/a/ae/Advanced-rifle-icon.png/164px-Advanced-rifle-icon.png) */
			ADVANCEDRIFLE = "weapon_advancedrifle",
			/** ![SpecialCarbine](https://wiki.rage.mp//images/thumb/b/b7/Special-carbine-icon.png/164px-Special-carbine-icon.png) */
			SPECIALCARBINE = "weapon_specialcarbine",
			/** ![SpecialCarbineMkII](https://wiki.rage.mp//images/thumb/3/34/Special-carbine-mk2-icon.png/164px-Special-carbine-mk2-icon.png) */
			SPECIALCARBINE_MK2 = "weapon_specialcarbine_mk2",
			/** ![BullpupRifle](https://wiki.rage.mp//images/thumb/0/09/Bullpup-rifle-icon.png/164px-Bullpup-rifle-icon.png) */
			BULLPUPRIFLE = "weapon_bullpuprifle",
			/** ![BullpupRifleMkII](https://wiki.rage.mp//images/thumb/e/e1/Bullpup-rifle-mk2-icon.png/164px-Bullpup-rifle-mk2-icon.png) */
			BULLPUPRIFLE_MK2 = "weapon_bullpuprifle_mk2",
			/** ![CompactRifle](https://wiki.rage.mp//images/thumb/c/c9/Compact-rifle-icon.png/164px-Compact-rifle-icon.png) */
			COMPACTRIFLE = "weapon_compactrifle",
			/** ![MilitaryRifle](https://wiki.rage.mp//images/thumb/0/01/Military-rifle-icon.png/164px-Military-rifle-icon.png) */
			MILITARYRIFLE = "weapon_militaryrifle",
			/** ![MG](https://wiki.rage.mp//images/thumb/9/98/Mg-icon.png/164px-Mg-icon.png) */
			MG = "weapon_mg",
			/** ![CombatMG](https://wiki.rage.mp//images/thumb/9/94/Combat-mg-icon.png/164px-Combat-mg-icon.png) */
			COMBATMG = "weapon_combatmg",
			/** ![CombatMGMkII](https://wiki.rage.mp//images/thumb/3/31/Combat-mg-mk2-icon.png/164px-Combat-mg-mk2-icon.png) */
			COMBATMG_MK2 = "weapon_combatmg_mk2",
			/** ![GusenbergSweeper](https://wiki.rage.mp//images/thumb/8/8f/Gusenberg-sweeper-icon.png/164px-Gusenberg-sweeper-icon.png) */
			GUSENBERG = "weapon_gusenberg",
			/** ![SniperRifle](https://wiki.rage.mp//images/thumb/e/ec/Sniper-rifle-icon.png/164px-Sniper-rifle-icon.png) */
			SNIPERRIFLE = "weapon_sniperrifle",
			/** ![HeavySniper](https://wiki.rage.mp//images/thumb/5/54/Heavy-sniper-icon.png/164px-Heavy-sniper-icon.png) */
			HEAVYSNIPER = "weapon_heavysniper",
			/** ![HeavySniperMkII](https://wiki.rage.mp//images/thumb/c/cf/Heavy-sniper-mk2-icon.png/164px-Heavy-sniper-mk2-icon.png) */
			HEAVYSNIPER_MK2 = "weapon_heavysniper_mk2",
			/** ![MarksmanRifle](https://wiki.rage.mp//images/thumb/2/22/Marksman-rifle-icon.png/164px-Marksman-rifle-icon.png) */
			MARKSMANRIFLE = "weapon_marksmanrifle",
			/** ![MarksmanRifleMkII](https://wiki.rage.mp//images/thumb/1/17/Marksman-rifle-mk2-icon.png/164px-Marksman-rifle-mk2-icon.png) */
			MARKSMANRIFLE_MK2 = "weapon_marksmanrifle_mk2",
			/** ![RPG](https://wiki.rage.mp//images/thumb/7/7d/Rocket-launcher-icon.png/164px-Rocket-launcher-icon.png) */
			RPG = "weapon_rpg",
			/** ![GrenadeLauncher](https://wiki.rage.mp//images/thumb/a/ae/Grenade-launcher-icon.png/164px-Grenade-launcher-icon.png) */
			GRENADELAUNCHER = "weapon_grenadelauncher",
			/** ![GrenadeLauncherSmoke](https://wiki.rage.mp//images/thumb/a/ae/Grenade-launcher-icon.png/164px-Grenade-launcher-icon.png) */
			GRENADELAUNCHER_SMOKE = "weapon_grenadelauncher_smoke",
			/** ![Minigun](https://wiki.rage.mp//images/thumb/8/8b/Minigun-icon.png/164px-Minigun-icon.png) */
			MINIGUN = "weapon_minigun",
			/** ![FireworkLauncher](https://wiki.rage.mp//images/thumb/5/54/Firework-launcher-icon.png/164px-Firework-launcher-icon.png) */
			FIREWORK = "weapon_firework",
			/** ![Railgun](https://wiki.rage.mp//images/thumb/a/ad/Railgun-icon.png/164px-Railgun-icon.png) */
			RAILGUN = "weapon_railgun",
			/** ![HomingLauncher](https://wiki.rage.mp//images/thumb/1/14/Homing-launcher-icon.png/164px-Homing-launcher-icon.png) */
			HOMINGLAUNCHER = "weapon_hominglauncher",
			/** ![CompactGrenadeLauncher](https://wiki.rage.mp//images/thumb/0/0d/Grenade-compact-launcher-icon.png/164px-Grenade-compact-launcher-icon.png) */
			COMPACTLAUNCHER = "weapon_compactlauncher",
			/** ![Widowmaker](https://wiki.rage.mp//images/thumb/e/ec/Widowmaker-icon.png/164px-Widowmaker-icon.png) */
			RAYMINIGUN = "weapon_rayminigun",
			/** ![Grenade](https://wiki.rage.mp//images/5/54/Grenade-icon.png) */
			GRENADE = "weapon_grenade",
			/** ![BZGas](https://wiki.rage.mp//images/thumb/d/d3/Bz-gas-icon.png/56px-Bz-gas-icon.png) */
			BZGAS = "weapon_bzgas",
			/** ![MolotovCocktail](https://wiki.rage.mp//images/thumb/4/46/Molotov-icon.png/120px-Molotov-icon.png) */
			MOLOTOV = "weapon_molotov",
			/** ![StickyBomb](https://wiki.rage.mp//images/3/3a/Sticky-bomb-icon.png) */
			STICKYBOMB = "weapon_stickybomb",
			/** ![ProximityMines](https://wiki.rage.mp//images/a/a8/Proximity-mines-icon.png) */
			PROXMINE = "weapon_proxmine",
			/** ![Snowballs](https://wiki.rage.mp//images/0/04/Snowball-icon.png) */
			SNOWBALL = "weapon_snowball",
			/** ![PipeBombs](https://wiki.rage.mp//images/thumb/d/dc/Pipe-bomb-icon.png/164px-Pipe-bomb-icon.png) */
			PIPEBOMB = "weapon_pipebomb",
			/** ![Baseball](https://wiki.rage.mp//images/4/4b/Ball-icon.png) */
			BALL = "weapon_ball",
			/** ![TearGas](https://wiki.rage.mp//images/thumb/8/8a/Tear-gas-icon.png/56px-Tear-gas-icon.png) */
			SMOKEGRENADE = "weapon_smokegrenade",
			/** ![Flare](https://wiki.rage.mp//images/0/09/Flare-icon.png) */
			FLARE = "weapon_flare",
			/** ![JerryCan](https://wiki.rage.mp//images/thumb/2/2b/Petrolcan-icon.png/94px-Petrolcan-icon.png) */
			PETROLCAN = "weapon_petrolcan",
			/** ![Parachute](https://wiki.rage.mp//images/thumb/2/24/Parachute-icon.png/93px-Parachute-icon.png) */
			GADGET_PARACHUTE = "gadget_parachute",
			/** ![FireExtinguisher](https://wiki.rage.mp//images/thumb/1/13/Fire2.png/51px-Fire2.png) */
			FIREEXTINGUISHER = "weapon_fireextinguisher",
			/** ![HazardousJerryCan](https://wiki.rage.mp//images/thumb/2/2b/Petrolcan-icon.png/94px-Petrolcan-icon.png) */
			HAZARDCAN = "weapon_hazardcan",
		}

		const enum Hash {
			/** ![AntiqueCavalryDagger](https://wiki.rage.mp//images/thumb/f/f5/Antique-cavalry-dagger-icon.png/164px-Antique-cavalry-dagger-icon.png) */
			DAGGER = 0x92A27487,
			/** ![BaseballBat](https://wiki.rage.mp//images/thumb/8/8b/Baseball-bat-icon.png/164px-Baseball-bat-icon.png) */
			BAT = 0x958A4A8F,
			/** ![BrokenBottle](https://wiki.rage.mp//images/5/5b/Broken-bottle-icon.png) */
			BOTTLE = 0xF9E6AA4B,
			/** ![Crowbar](https://wiki.rage.mp//images/thumb/8/8a/Crowbar-icon.png/164px-Crowbar-icon.png) */
			CROWBAR = 0x84BD7BFD,
			/** ![Fist](https://wiki.rage.mp//images/b/b7/Fist-icon.png) */
			UNARMED = 0xA2719263,
			/** ![Flashlight](https://wiki.rage.mp//images/thumb/8/85/Flashlight-icon.png/164px-Flashlight-icon.png) */
			FLASHLIGHT = 0x8BB05FD7,
			/** ![GolfClub](https://wiki.rage.mp//images/thumb/c/cb/Golf-club-icon.png/164px-Golf-club-icon.png) */
			GOLFCLUB = 0x440E4788,
			/** ![Hammer](https://wiki.rage.mp//images/thumb/e/ec/Hammer-icon.png/164px-Hammer-icon.png) */
			HAMMER = 0x4E875F73,
			/** ![Hatchet](https://wiki.rage.mp//images/thumb/e/eb/Hatchet-icon.png/164px-Hatchet-icon.png) */
			HATCHET = 0xF9DCBF2D,
			/** ![BrassKnuckles](https://wiki.rage.mp//images/b/b7/Knuckles-icon.png) */
			KNUCKLE = 0xD8DF3C3C,
			/** ![Knife](https://wiki.rage.mp//images/thumb/8/8c/Knife-icon.png/164px-Knife-icon.png) */
			KNIFE = 0x99B507EA,
			/** ![Machete](https://wiki.rage.mp//images/thumb/d/dc/Machete-icon.png/164px-Machete-icon.png) */
			MACHETE = 0xDD5DF8D9,
			/** ![Switchblade](https://wiki.rage.mp//images/thumb/c/ce/Switch-blade-icon.png/164px-Switch-blade-icon.png) */
			SWITCHBLADE = 0xDFE37640,
			/** ![Nightstick](https://wiki.rage.mp//images/thumb/e/e6/Nightstick-icon.png/164px-Nightstick-icon.png) */
			NIGHTSTICK = 0x678B81B1,
			/** ![PipeWrench](https://wiki.rage.mp//images/thumb/2/22/Pipe-wrench-icon.png/164px-Pipe-wrench-icon.png) */
			WRENCH = 0x19044EE0,
			/** ![BattleAxe](https://wiki.rage.mp//images/thumb/3/3b/Battle-axe-icon.png/164px-Battle-axe-icon.png) */
			BATTLEAXE = 0xCD274149,
			/** ![PoolCue](https://wiki.rage.mp//images/thumb/3/3a/Pool-cue-icon.png/164px-Pool-cue-icon.png) */
			POOLCUE = 0x94117305,
			/** ![StoneHatchet](https://wiki.rage.mp//images/thumb/2/21/Stone-hatchet-icon.png/164px-Stone-hatchet-icon.png) */
			STONE_HATCHET = 0x3813FC08,
			/** ![Pistol](https://wiki.rage.mp//images/9/95/Pistol-icon.png) */
			PISTOL = 0x1B06D571,
			/** ![PistolMkII](https://wiki.rage.mp//images/4/43/Pistol-mk2-icon.png) */
			PISTOL_MK2 = 0xBFE256D4,
			/** ![CombatPistol](https://wiki.rage.mp//images/1/16/Combat-pistol-icon.png) */
			COMBATPISTOL = 0x5EF9FEC4,
			/** ![APPistol](https://wiki.rage.mp//images/4/4d/Appistol-icon.png) */
			APPISTOL = 0x22D8FE39,
			/** ![StunGun](https://wiki.rage.mp//images/3/3c/Stungun-icon.png) */
			STUNGUN = 0x3656C8C1,
			/** ![Pistol.50](https://wiki.rage.mp//images/c/c5/Pistol.50-icon.png) */
			PISTOL50 = 0x99AEEB3B,
			/** ![SNSPistol](https://wiki.rage.mp//images/9/96/Sns-pistol-icon.png) */
			SNSPISTOL = 0xBFD21232,
			/** ![SNSPistolMkII](https://wiki.rage.mp//images/1/16/Sns-pistol-mk2-icon.png) */
			SNSPISTOL_MK2 = 0x88374054,
			/** ![HeavyPistol](https://wiki.rage.mp//images/7/78/Heavy-pistol-icon.png) */
			HEAVYPISTOL = 0xD205520E,
			/** ![VintagePistol](https://wiki.rage.mp//images/9/97/Vintage-pistol-icon.png) */
			VINTAGEPISTOL = 0x83839C4,
			/** ![FlareGun](https://wiki.rage.mp//images/0/0d/Flaregun-icon.png) */
			FLAREGUN = 0x47757124,
			/** ![MarksmanPistol](https://wiki.rage.mp//images/thumb/4/47/Marksman-pistol-icon.png/164px-Marksman-pistol-icon.png) */
			MARKSMANPISTOL = 0xDC4DB296,
			/** ![HeavyRevolver](https://wiki.rage.mp//images/thumb/9/93/Heavy-revolver-icon.png/164px-Heavy-revolver-icon.png) */
			REVOLVER = 0xC1B3C3D1,
			/** ![HeavyRevolverMkII](https://wiki.rage.mp//images/thumb/c/c0/Heavy-revolver-mk2-icon.png/164px-Heavy-revolver-mk2-icon.png) */
			REVOLVER_MK2 = 0xCB96392F,
			/** ![DoubleActionRevolver](https://wiki.rage.mp//images/thumb/4/45/Double-action-revolver-icon.png/164px-Double-action-revolver-icon.png) */
			DOUBLEACTION = 0x97EA20B8,
			/** ![Up-n-Atomizer](https://wiki.rage.mp//images/thumb/8/89/Up-n-atomizer-icon.png/164px-Up-n-atomizer-icon.png) */
			RAYPISTOL = 0xAF3696A1,
			/** ![CeramicPistol](https://wiki.rage.mp//images/a/ad/Ceramic-pistol-icon.png) */
			CERAMICPISTOL = 0x2B5EF5EC,
			/** ![NavyRevolver](https://wiki.rage.mp//images/thumb/1/15/Navy-revolver-icon.png/164px-Navy-revolver-icon.png) */
			NAVYREVOLVER = 0x917F6C8C,
			/** ![PericoPistol](https://wiki.rage.mp//images/thumb/3/31/Perico-pistol-icon.png/164px-Perico-pistol-icon.png) */
			GADGETPISTOL = 0x57A4368C,
			/** ![MicroSMG](https://wiki.rage.mp//images/thumb/3/3a/Micro-smg-icon.png/164px-Micro-smg-icon.png) */
			MICROSMG = 0x13532244,
			/** ![SMG](https://wiki.rage.mp//images/thumb/3/30/Smg-icon.png/164px-Smg-icon.png) */
			SMG = 0x2BE6766B,
			/** ![SMGMkII](https://wiki.rage.mp//images/thumb/d/d1/Smg-mk2-icon.png/164px-Smg-mk2-icon.png) */
			SMG_MK2 = 0x78A97CD0,
			/** ![AssaultSMG](https://wiki.rage.mp//images/thumb/3/30/Assault-smg-icon.png/164px-Assault-smg-icon.png) */
			ASSAULTSMG = 0xEFE7E2DF,
			/** ![CombatPDW](https://wiki.rage.mp//images/thumb/4/45/Combat-pdw-icon.png/164px-Combat-pdw-icon.png) */
			COMBATPDW = 0x0A3D4D34,
			/** ![MachinePistol](https://wiki.rage.mp//images/thumb/2/24/Machine-pistol-icon.png/164px-Machine-pistol-icon.png) */
			MACHINEPISTOL = 0xDB1AA450,
			/** ![MiniSMG](https://wiki.rage.mp//images/thumb/d/d3/Mini-smg-icon.png/164px-Mini-smg-icon.png) */
			MINISMG = 0xBD248B55,
			/** ![UnholyHellbringer](https://wiki.rage.mp//images/thumb/8/8f/Unholy-hellbringer-icon.png/164px-Unholy-hellbringer-icon.png) */
			RAYCARBINE = 0x476BF155,
			/** ![PumpShotgun](https://wiki.rage.mp//images/thumb/0/09/Pump-shotgun-icon.png/164px-Pump-shotgun-icon.png) */
			PUMPSHOTGUN = 0x1D073A89,
			/** ![PumpShotgunMkII](https://wiki.rage.mp//images/thumb/6/69/Pump-shotgun-mk2-icon.png/164px-Pump-shotgun-mk2-icon.png) */
			PUMPSHOTGUN_MK2 = 0x555AF99A,
			/** ![Sawed-OffShotgun](https://wiki.rage.mp//images/thumb/b/ba/Sawed-off-shotgun-icon.png/164px-Sawed-off-shotgun-icon.png) */
			SAWNOFFSHOTGUN = 0x7846A318,
			/** ![AssaultShotgun](https://wiki.rage.mp//images/thumb/e/e3/Assault-shotgun-icon.png/164px-Assault-shotgun-icon.png) */
			ASSAULTSHOTGUN = 0xE284C527,
			/** ![BullpupShotgun](https://wiki.rage.mp//images/thumb/7/7f/Bullpup-shotgun-icon.png/164px-Bullpup-shotgun-icon.png) */
			BULLPUPSHOTGUN = 0x9D61E50F,
			/** ![Musket](https://wiki.rage.mp//images/thumb/8/8c/Musket-icon.png/164px-Musket-icon.png) */
			MUSKET = 0xA89CB99E,
			/** ![HeavyShotgun](https://wiki.rage.mp//images/thumb/5/5d/Heavy-shotgun-icon.png/164px-Heavy-shotgun-icon.png) */
			HEAVYSHOTGUN = 0x3AABBBAA,
			/** ![DoubleBarrelShotgun](https://wiki.rage.mp//images/thumb/8/8d/Double-barrel-shotgun-icon.png/164px-Double-barrel-shotgun-icon.png) */
			DBSHOTGUN = 0xEF951FBB,
			/** ![SweeperShotgun](https://wiki.rage.mp//images/thumb/a/a8/Sweeper-shotgun-icon.png/164px-Sweeper-shotgun-icon.png) */
			AUTOSHOTGUN = 0x12E82D3D,
			/** ![CombatShotgun](https://wiki.rage.mp//images/thumb/5/50/Combat-shotgun-icon.png/164px-Combat-shotgun-icon.png) */
			COMBATSHOTGUN = 0x5A96BA4,
			/** ![AssaultRifle](https://wiki.rage.mp//images/thumb/6/61/Assault-rifle-icon.png/164px-Assault-rifle-icon.png) */
			ASSAULTRIFLE = 0xBFEFFF6D,
			/** ![AssaultRifleMkII](https://wiki.rage.mp//images/thumb/6/63/Assault-rifle-mk2-icon.png/164px-Assault-rifle-mk2-icon.png) */
			ASSAULTRIFLE_MK2 = 0x394F415C,
			/** ![CarbineRifle](https://wiki.rage.mp//images/thumb/7/73/Carbine-rifle-icon.png/164px-Carbine-rifle-icon.png) */
			CARBINERIFLE = 0x83BF0278,
			/** ![CarbineRifleMkII](https://wiki.rage.mp//images/thumb/3/3f/Carbine-rifle-mk2-icon.png/164px-Carbine-rifle-mk2-icon.png) */
			CARBINERIFLE_MK2 = 0xFAD1F1C9,
			/** ![AdvancedRifle](https://wiki.rage.mp//images/thumb/a/ae/Advanced-rifle-icon.png/164px-Advanced-rifle-icon.png) */
			ADVANCEDRIFLE = 0xAF113F99,
			/** ![SpecialCarbine](https://wiki.rage.mp//images/thumb/b/b7/Special-carbine-icon.png/164px-Special-carbine-icon.png) */
			SPECIALCARBINE = 0xC0A3098D,
			/** ![SpecialCarbineMkII](https://wiki.rage.mp//images/thumb/3/34/Special-carbine-mk2-icon.png/164px-Special-carbine-mk2-icon.png) */
			SPECIALCARBINE_MK2 = 0x969C3D67,
			/** ![BullpupRifle](https://wiki.rage.mp//images/thumb/0/09/Bullpup-rifle-icon.png/164px-Bullpup-rifle-icon.png) */
			BULLPUPRIFLE = 0x7F229F94,
			/** ![BullpupRifleMkII](https://wiki.rage.mp//images/thumb/e/e1/Bullpup-rifle-mk2-icon.png/164px-Bullpup-rifle-mk2-icon.png) */
			BULLPUPRIFLE_MK2 = 0x84D6FAFD,
			/** ![CompactRifle](https://wiki.rage.mp//images/thumb/c/c9/Compact-rifle-icon.png/164px-Compact-rifle-icon.png) */
			COMPACTRIFLE = 0x624FE830,
			/** ![MilitaryRifle](https://wiki.rage.mp//images/thumb/0/01/Military-rifle-icon.png/164px-Military-rifle-icon.png) */
			MILITARYRIFLE = 0x9D1F17E6,
			/** ![MG](https://wiki.rage.mp//images/thumb/9/98/Mg-icon.png/164px-Mg-icon.png) */
			MG = 0x9D07F764,
			/** ![CombatMG](https://wiki.rage.mp//images/thumb/9/94/Combat-mg-icon.png/164px-Combat-mg-icon.png) */
			COMBATMG = 0x7FD62962,
			/** ![CombatMGMkII](https://wiki.rage.mp//images/thumb/3/31/Combat-mg-mk2-icon.png/164px-Combat-mg-mk2-icon.png) */
			COMBATMG_MK2 = 0xDBBD7280,
			/** ![GusenbergSweeper](https://wiki.rage.mp//images/thumb/8/8f/Gusenberg-sweeper-icon.png/164px-Gusenberg-sweeper-icon.png) */
			GUSENBERG = 0x61012683,
			/** ![SniperRifle](https://wiki.rage.mp//images/thumb/e/ec/Sniper-rifle-icon.png/164px-Sniper-rifle-icon.png) */
			SNIPERRIFLE = 0x05FC3C11,
			/** ![HeavySniper](https://wiki.rage.mp//images/thumb/5/54/Heavy-sniper-icon.png/164px-Heavy-sniper-icon.png) */
			HEAVYSNIPER = 0x0C472FE2,
			/** ![HeavySniperMkII](https://wiki.rage.mp//images/thumb/c/cf/Heavy-sniper-mk2-icon.png/164px-Heavy-sniper-mk2-icon.png) */
			HEAVYSNIPER_MK2 = 0xA914799,
			/** ![MarksmanRifle](https://wiki.rage.mp//images/thumb/2/22/Marksman-rifle-icon.png/164px-Marksman-rifle-icon.png) */
			MARKSMANRIFLE = 0xC734385A,
			/** ![MarksmanRifleMkII](https://wiki.rage.mp//images/thumb/1/17/Marksman-rifle-mk2-icon.png/164px-Marksman-rifle-mk2-icon.png) */
			MARKSMANRIFLE_MK2 = 0x6A6C02E0,
			/** ![RPG](https://wiki.rage.mp//images/thumb/7/7d/Rocket-launcher-icon.png/164px-Rocket-launcher-icon.png) */
			RPG = 0xB1CA77B1,
			/** ![GrenadeLauncher](https://wiki.rage.mp//images/thumb/a/ae/Grenade-launcher-icon.png/164px-Grenade-launcher-icon.png) */
			GRENADELAUNCHER = 0xA284510B,
			/** ![GrenadeLauncherSmoke](https://wiki.rage.mp//images/thumb/a/ae/Grenade-launcher-icon.png/164px-Grenade-launcher-icon.png) */
			GRENADELAUNCHER_SMOKE = 0x4DD2DC56,
			/** ![Minigun](https://wiki.rage.mp//images/thumb/8/8b/Minigun-icon.png/164px-Minigun-icon.png) */
			MINIGUN = 0x42BF8A85,
			/** ![FireworkLauncher](https://wiki.rage.mp//images/thumb/5/54/Firework-launcher-icon.png/164px-Firework-launcher-icon.png) */
			FIREWORK = 0x7F7497E5,
			/** ![Railgun](https://wiki.rage.mp//images/thumb/a/ad/Railgun-icon.png/164px-Railgun-icon.png) */
			RAILGUN = 0x6D544C99,
			/** ![HomingLauncher](https://wiki.rage.mp//images/thumb/1/14/Homing-launcher-icon.png/164px-Homing-launcher-icon.png) */
			HOMINGLAUNCHER = 0x63AB0442,
			/** ![CompactGrenadeLauncher](https://wiki.rage.mp//images/thumb/0/0d/Grenade-compact-launcher-icon.png/164px-Grenade-compact-launcher-icon.png) */
			COMPACTLAUNCHER = 0x0781FE4A,
			/** ![Widowmaker](https://wiki.rage.mp//images/thumb/e/ec/Widowmaker-icon.png/164px-Widowmaker-icon.png) */
			RAYMINIGUN = 0xB62D1F67,
			/** ![Grenade](https://wiki.rage.mp//images/5/54/Grenade-icon.png) */
			GRENADE = 0x93E220BD,
			/** ![BZGas](https://wiki.rage.mp//images/thumb/d/d3/Bz-gas-icon.png/56px-Bz-gas-icon.png) */
			BZGAS = 0xA0973D5E,
			/** ![MolotovCocktail](https://wiki.rage.mp//images/thumb/4/46/Molotov-icon.png/120px-Molotov-icon.png) */
			MOLOTOV = 0x24B17070,
			/** ![StickyBomb](https://wiki.rage.mp//images/3/3a/Sticky-bomb-icon.png) */
			STICKYBOMB = 0x2C3731D9,
			/** ![ProximityMines](https://wiki.rage.mp//images/a/a8/Proximity-mines-icon.png) */
			PROXMINE = 0xAB564B93,
			/** ![Snowballs](https://wiki.rage.mp//images/0/04/Snowball-icon.png) */
			SNOWBALL = 0x787F0BB,
			/** ![PipeBombs](https://wiki.rage.mp//images/thumb/d/dc/Pipe-bomb-icon.png/164px-Pipe-bomb-icon.png) */
			PIPEBOMB = 0xBA45E8B8,
			/** ![Baseball](https://wiki.rage.mp//images/4/4b/Ball-icon.png) */
			BALL = 0x23C9F95C,
			/** ![TearGas](https://wiki.rage.mp//images/thumb/8/8a/Tear-gas-icon.png/56px-Tear-gas-icon.png) */
			SMOKEGRENADE = 0xFDBC8A50,
			/** ![Flare](https://wiki.rage.mp//images/0/09/Flare-icon.png) */
			FLARE = 0x497FACC3,
			/** ![JerryCan](https://wiki.rage.mp//images/thumb/2/2b/Petrolcan-icon.png/94px-Petrolcan-icon.png) */
			PETROLCAN = 0x34A67B97,
			/** ![Parachute](https://wiki.rage.mp//images/thumb/2/24/Parachute-icon.png/93px-Parachute-icon.png) */
			GADGET_PARACHUTE = 0xFBAB5776,
			/** ![FireExtinguisher](https://wiki.rage.mp//images/thumb/1/13/Fire2.png/51px-Fire2.png) */
			FIREEXTINGUISHER = 0x060EC506,
			/** ![HazardousJerryCan](https://wiki.rage.mp//images/thumb/2/2b/Petrolcan-icon.png/94px-Petrolcan-icon.png) */
			HAZARDCAN = 0xBA536372,
		}
	}
}

declare namespace RageEnums.Hashes {
	export import Weapon = RageEnums.Weapons.Hash;
}
