declare namespace RageEnums {
	const enum ScreenshotType {
		JPG = 0,
		PNG = 1,
		BMP = 2
	}

	const enum VehicleBones {
		CHASSIS = 'chassis',
		CHASSIS_LOWLOD = 'chassis_lowlod',
		CHASSIS_DUMMY = 'chassis_dummy',
		SEAT_DSIDE_F = 'seat_dside_f',
		SEAT_DSIDE_R = 'seat_dside_r',
		SEAT_DSIDE_R1 = 'seat_dside_r1',
		SEAT_DSIDE_R2 = 'seat_dside_r2',
		SEAT_DSIDE_R3 = 'seat_dside_r3',
		SEAT_DSIDE_R4 = 'seat_dside_r4',
		SEAT_DSIDE_R5 = 'seat_dside_r5',
		SEAT_DSIDE_R6 = 'seat_dside_r6',
		SEAT_DSIDE_R7 = 'seat_dside_r7',
		SEAT_PSIDE_F = 'seat_pside_f',
		SEAT_PSIDE_R = 'seat_pside_r',
		SEAT_PSIDE_R1 = 'seat_pside_r1',
		SEAT_PSIDE_R2 = 'seat_pside_r2',
		SEAT_PSIDE_R3 = 'seat_pside_r3',
		SEAT_PSIDE_R4 = 'seat_pside_r4',
		SEAT_PSIDE_R5 = 'seat_pside_r5',
		SEAT_PSIDE_R6 = 'seat_pside_r6',
		SEAT_PSIDE_R7 = 'seat_pside_r7',
		WINDOW_LF1 = 'window_lf1',
		WINDOW_LF2 = 'window_lf2',
		WINDOW_LF3 = 'window_lf3',
		WINDOW_RF1 = 'window_rf1',
		WINDOW_RF2 = 'window_rf2',
		WINDOW_RF3 = 'window_rf3',
		WINDOW_LR1 = 'window_lr1',
		WINDOW_LR2 = 'window_lr2',
		WINDOW_LR3 = 'window_lr3',
		WINDOW_RR1 = 'window_rr1',
		WINDOW_RR2 = 'window_rr2',
		WINDOW_RR3 = 'window_rr3',
		DOOR_DSIDE_F = 'door_dside_f',
		DOOR_DSIDE_R = 'door_dside_r',
		DOOR_PSIDE_F = 'door_pside_f',
		DOOR_PSIDE_R = 'door_pside_r',
		HANDLE_DSIDE_F = 'handle_dside_f',
		HANDLE_DSIDE_R = 'handle_dside_r',
		HANDLE_PSIDE_F = 'handle_pside_f',
		HANDLE_PSIDE_R = 'handle_pside_r',
		WHEEL_LF = 'wheel_lf',
		WHEEL_RF = 'wheel_rf',
		WHEEL_LM1 = 'wheel_lm1',
		WHEEL_RM1 = 'wheel_rm1',
		WHEEL_LM2 = 'wheel_lm2',
		WHEEL_RM2 = 'wheel_rm2',
		WHEEL_LM3 = 'wheel_lm3',
		WHEEL_RM3 = 'wheel_rm3',
		WHEEL_LR = 'wheel_lr',
		WHEEL_RR = 'wheel_rr',
		SUSPENSION_LF = 'suspension_lf',
		SUSPENSION_RF = 'suspension_rf',
		SUSPENSION_LM = 'suspension_lm',
		SUSPENSION_RM = 'suspension_rm',
		SUSPENSION_LR = 'suspension_lr',
		SUSPENSION_RR = 'suspension_rr',
		SPRING_RF = 'spring_rf',
		SPRING_LF = 'spring_lf',
		SPRING_RR = 'spring_rr',
		SPRING_LR = 'spring_lr',
		TRANSMISSION_F = 'transmission_f',
		TRANSMISSION_M = 'transmission_m',
		TRANSMISSION_R = 'transmission_r',
		HUB_LF = 'hub_lf',
		HUB_RF = 'hub_rf',
		HUB_LM1 = 'hub_lm1',
		HUB_RM1 = 'hub_rm1',
		HUB_LM2 = 'hub_lm2',
		HUB_RM2 = 'hub_rm2',
		HUB_LM3 = 'hub_lm3',
		HUB_RM3 = 'hub_rm3',
		HUB_LR = 'hub_lr',
		HUB_RR = 'hub_rr',
		WINDSCREEN = 'windscreen',
		WINDSCREEN_R = 'windscreen_r',
		WINDOW_LF = 'window_lf',
		WINDOW_RF = 'window_rf',
		WINDOW_LR = 'window_lr',
		WINDOW_RR = 'window_rr',
		WINDOW_LM = 'window_lm',
		WINDOW_RM = 'window_rm',
		BODYSHELL = 'bodyshell',
		BUMPER_F = 'bumper_f',
		BUMPER_R = 'bumper_r',
		WING_RF = 'wing_rf',
		WING_LF = 'wing_lf',
		BONNET = 'bonnet',
		BOOT = 'boot',
		EXHAUST = 'exhaust',
		EXHAUST_2 = 'exhaust_2',
		EXHAUST_3 = 'exhaust_3',
		EXHAUST_4 = 'exhaust_4',
		EXHAUST_5 = 'exhaust_5',
		EXHAUST_6 = 'exhaust_6',
		EXHAUST_7 = 'exhaust_7',
		EXHAUST_8 = 'exhaust_8',
		EXHAUST_9 = 'exhaust_9',
		EXHAUST_10 = 'exhaust_10',
		EXHAUST_11 = 'exhaust_11',
		EXHAUST_12 = 'exhaust_12',
		EXHAUST_13 = 'exhaust_13',
		EXHAUST_14 = 'exhaust_14',
		EXHAUST_15 = 'exhaust_15',
		EXHAUST_16 = 'exhaust_16',
		ENGINE = 'engine',
		OVERHEAT = 'overheat',
		OVERHEAT_2 = 'overheat_2',
		PETROLCAP = 'petrolcap',
		PETROLTANK = 'petroltank',
		PETROLTANK_L = 'petroltank_l',
		PETROLTANK_R = 'petroltank_r',
		STEERING = 'steering',
		HBGRIP_L = 'hbgrip_l',
		HBGRIP_R = 'hbgrip_r',
		HEADLIGHT_L = 'headlight_l',
		HEADLIGHT_R = 'headlight_r',
		TAILLIGHT_L = 'taillight_l',
		TAILLIGHT_R = 'taillight_r',
		INDICATOR_LF = 'indicator_lf',
		INDICATOR_RF = 'indicator_rf',
		INDICATOR_LR = 'indicator_lr',
		INDICATOR_RR = 'indicator_rr',
		BRAKELIGHT_L = 'brakelight_l',
		BRAKELIGHT_R = 'brakelight_r',
		BRAKELIGHT_M = 'brakelight_m',
		REVERSINGLIGHT_L = 'reversinglight_l',
		REVERSINGLIGHT_R = 'reversinglight_r',
		EXTRALIGHT_1 = 'extralight_1',
		EXTRALIGHT_2 = 'extralight_2',
		EXTRALIGHT_3 = 'extralight_3',
		EXTRALIGHT_4 = 'extralight_4',
		NUMBERPLATE = 'numberplate',
		INTERIORLIGHT = 'interiorlight',
		SIREN1 = 'siren1',
		SIREN2 = 'siren2',
		SIREN3 = 'siren3',
		SIREN4 = 'siren4',
		SIREN5 = 'siren5',
		SIREN6 = 'siren6',
		SIREN7 = 'siren7',
		SIREN8 = 'siren8',
		SIREN9 = 'siren9',
		SIREN10 = 'siren10',
		SIREN11 = 'siren11',
		SIREN12 = 'siren12',
		SIREN13 = 'siren13',
		SIREN14 = 'siren14',
		SIREN15 = 'siren15',
		SIREN16 = 'siren16',
		SIREN17 = 'siren17',
		SIREN18 = 'siren18',
		SIREN19 = 'siren19',
		SIREN20 = 'siren20',
		SIREN_GLASS1 = 'siren_glass1',
		SIREN_GLASS2 = 'siren_glass2',
		SIREN_GLASS3 = 'siren_glass3',
		SIREN_GLASS4 = 'siren_glass4',
		SIREN_GLASS5 = 'siren_glass5',
		SIREN_GLASS6 = 'siren_glass6',
		SIREN_GLASS7 = 'siren_glass7',
		SIREN_GLASS8 = 'siren_glass8',
		SIREN_GLASS9 = 'siren_glass9',
		SIREN_GLASS10 = 'siren_glass10',
		SIREN_GLASS11 = 'siren_glass11',
		SIREN_GLASS12 = 'siren_glass12',
		SIREN_GLASS13 = 'siren_glass13',
		SIREN_GLASS14 = 'siren_glass14',
		SIREN_GLASS15 = 'siren_glass15',
		SIREN_GLASS16 = 'siren_glass16',
		SIREN_GLASS17 = 'siren_glass17',
		SIREN_GLASS18 = 'siren_glass18',
		SIREN_GLASS19 = 'siren_glass19',
		SIREN_GLASS20 = 'siren_glass20',
		SPOILER = 'spoiler',
		STRUTS = 'struts',
		MISC_A = 'misc_a',
		MISC_B = 'misc_b',
		MISC_C = 'misc_c',
		MISC_D = 'misc_d',
		MISC_E = 'misc_e',
		MISC_F = 'misc_f',
		MISC_G = 'misc_g',
		MISC_H = 'misc_h',
		MISC_I = 'misc_i',
		MISC_J = 'misc_j',
		MISC_K = 'misc_k',
		MISC_L = 'misc_l',
		MISC_M = 'misc_m',
		MISC_N = 'misc_n',
		MISC_O = 'misc_o',
		MISC_P = 'misc_p',
		MISC_Q = 'misc_q',
		MISC_R = 'misc_r',
		MISC_S = 'misc_s',
		MISC_T = 'misc_t',
		MISC_U = 'misc_u',
		MISC_V = 'misc_v',
		MISC_W = 'misc_w',
		MISC_X = 'misc_x',
		MISC_Y = 'misc_y',
		MISC_Z = 'misc_z',
		MISC_1 = 'misc_1',
		MISC_2 = 'misc_2',
		WEAPON_1A = 'weapon_1a',
		WEAPON_1B = 'weapon_1b',
		WEAPON_1C = 'weapon_1c',
		WEAPON_1D = 'weapon_1d',
		WEAPON_1A_ROT = 'weapon_1a_rot',
		WEAPON_1B_ROT = 'weapon_1b_rot',
		WEAPON_1C_ROT = 'weapon_1c_rot',
		WEAPON_1D_ROT = 'weapon_1d_rot',
		WEAPON_2A = 'weapon_2a',
		WEAPON_2B = 'weapon_2b',
		WEAPON_2C = 'weapon_2c',
		WEAPON_2D = 'weapon_2d',
		WEAPON_2A_ROT = 'weapon_2a_rot',
		WEAPON_2B_ROT = 'weapon_2b_rot',
		WEAPON_2C_ROT = 'weapon_2c_rot',
		WEAPON_2D_ROT = 'weapon_2d_rot',
		WEAPON_3A = 'weapon_3a',
		WEAPON_3B = 'weapon_3b',
		WEAPON_3C = 'weapon_3c',
		WEAPON_3D = 'weapon_3d',
		WEAPON_3A_ROT = 'weapon_3a_rot',
		WEAPON_3B_ROT = 'weapon_3b_rot',
		WEAPON_3C_ROT = 'weapon_3c_rot',
		WEAPON_3D_ROT = 'weapon_3d_rot',
		WEAPON_4A = 'weapon_4a',
		WEAPON_4B = 'weapon_4b',
		WEAPON_4C = 'weapon_4c',
		WEAPON_4D = 'weapon_4d',
		WEAPON_4A_ROT = 'weapon_4a_rot',
		WEAPON_4B_ROT = 'weapon_4b_rot',
		WEAPON_4C_ROT = 'weapon_4c_rot',
		WEAPON_4D_ROT = 'weapon_4d_rot',
		TURRET_1BASE = 'turret_1base',
		TURRET_1BARREL = 'turret_1barrel',
		TURRET_2BASE = 'turret_2base',
		TURRET_2BARREL = 'turret_2barrel',
		TURRET_3BASE = 'turret_3base',
		TURRET_3BARREL = 'turret_3barrel',
		AMMOBELT = 'ammobelt',
		SEARCHLIGHT_BASE = 'searchlight_base',
		SEARCHLIGHT_LIGHT = 'searchlight_light',
		ATTACH_FEMALE = 'attach_female',
		ROOF = 'roof',
		ROOF2 = 'roof2',
		SOFT_1 = 'soft_1',
		SOFT_2 = 'soft_2',
		SOFT_3 = 'soft_3',
		SOFT_4 = 'soft_4',
		SOFT_5 = 'soft_5',
		SOFT_6 = 'soft_6',
		SOFT_7 = 'soft_7',
		SOFT_8 = 'soft_8',
		SOFT_9 = 'soft_9',
		SOFT_10 = 'soft_10',
		SOFT_11 = 'soft_11',
		SOFT_12 = 'soft_12',
		SOFT_13 = 'soft_13',
		FORKS = 'forks',
		MAST = 'mast',
		CARRIAGE = 'carriage',
		FORK_L = 'fork_l',
		FORK_R = 'fork_r',
		FORKS_ATTACH = 'forks_attach',
		FRAME_1 = 'frame_1',
		FRAME_2 = 'frame_2',
		FRAME_3 = 'frame_3',
		FRAME_PICKUP_1 = 'frame_pickup_1',
		FRAME_PICKUP_2 = 'frame_pickup_2',
		FRAME_PICKUP_3 = 'frame_pickup_3',
		FRAME_PICKUP_4 = 'frame_pickup_4',
		FREIGHT_CONT = 'freight_cont',
		FREIGHT_BOGEY = 'freight_bogey',
		FREIGHTGRAIN_SLIDEDOOR = 'freightgrain_slidedoor',
		DOOR_HATCH_R = 'door_hatch_r',
		DOOR_HATCH_L = 'door_hatch_l',
		TOW_ARM = 'tow_arm',
		TOW_MOUNT_A = 'tow_mount_a',
		TOW_MOUNT_B = 'tow_mount_b',
		TIPPER = 'tipper',
		COMBINE_REEL = 'combine_reel',
		COMBINE_AUGER = 'combine_auger',
		SLIPSTREAM_L = 'slipstream_l',
		SLIPSTREAM_R = 'slipstream_r',
		ARM_1 = 'arm_1',
		ARM_2 = 'arm_2',
		ARM_3 = 'arm_3',
		ARM_4 = 'arm_4',
		SCOOP = 'scoop',
		BOOM = 'boom',
		STICK = 'stick',
		BUCKET = 'bucket',
		SHOVEL_2 = 'shovel_2',
		SHOVEL_3 = 'shovel_3',
		LOOKAT_UPPRPISTON_HEAD = 'Lookat_UpprPiston_head',
		LOOKAT_LOWRPISTON_BOOM = 'Lookat_LowrPiston_boom',
		BOOM_DRIVER = 'Boom_Driver',
		CUTTER_DRIVER = 'cutter_driver',
		VEHICLE_BLOCKER = 'vehicle_blocker',
		EXTRA_1 = 'extra_1',
		EXTRA_2 = 'extra_2',
		EXTRA_3 = 'extra_3',
		EXTRA_4 = 'extra_4',
		EXTRA_5 = 'extra_5',
		EXTRA_6 = 'extra_6',
		EXTRA_7 = 'extra_7',
		EXTRA_8 = 'extra_8',
		EXTRA_9 = 'extra_9',
		EXTRA_TEN = 'extra_ten',
		EXTRA_11 = 'extra_11',
		EXTRA_12 = 'extra_12',
		BREAK_EXTRA_1 = 'break_extra_1',
		BREAK_EXTRA_2 = 'break_extra_2',
		BREAK_EXTRA_3 = 'break_extra_3',
		BREAK_EXTRA_4 = 'break_extra_4',
		BREAK_EXTRA_5 = 'break_extra_5',
		BREAK_EXTRA_6 = 'break_extra_6',
		BREAK_EXTRA_7 = 'break_extra_7',
		BREAK_EXTRA_8 = 'break_extra_8',
		BREAK_EXTRA_9 = 'break_extra_9',
		BREAK_EXTRA_10 = 'break_extra_10',
		MOD_COL_1 = 'mod_col_1',
		MOD_COL_2 = 'mod_col_2',
		MOD_COL_3 = 'mod_col_3',
		MOD_COL_4 = 'mod_col_4',
		MOD_COL_5 = 'mod_col_5',
		HANDLEBARS = 'handlebars',
		FORKS_U = 'forks_u',
		FORKS_L = 'forks_l',
		WHEEL_F = 'wheel_f',
		SWINGARM = 'swingarm',
		WHEEL_R = 'wheel_r',
		CRANK = 'crank',
		PEDAL_R = 'pedal_r',
		PEDAL_L = 'pedal_l',
		STATIC_PROP = 'static_prop',
		MOVING_PROP = 'moving_prop',
		STATIC_PROP2 = 'static_prop2',
		MOVING_PROP2 = 'moving_prop2',
		RUDDER = 'rudder',
		RUDDER2 = 'rudder2',
		WHEEL_RF1_DUMMY = 'wheel_rf1_dummy',
		WHEEL_RF2_DUMMY = 'wheel_rf2_dummy',
		WHEEL_RF3_DUMMY = 'wheel_rf3_dummy',
		WHEEL_RB1_DUMMY = 'wheel_rb1_dummy',
		WHEEL_RB2_DUMMY = 'wheel_rb2_dummy',
		WHEEL_RB3_DUMMY = 'wheel_rb3_dummy',
		WHEEL_LF1_DUMMY = 'wheel_lf1_dummy',
		WHEEL_LF2_DUMMY = 'wheel_lf2_dummy',
		WHEEL_LF3_DUMMY = 'wheel_lf3_dummy',
		WHEEL_LB1_DUMMY = 'wheel_lb1_dummy',
		WHEEL_LB2_DUMMY = 'wheel_lb2_dummy',
		WHEEL_LB3_DUMMY = 'wheel_lb3_dummy',
		BOGIE_FRONT = 'bogie_front',
		BOGIE_REAR = 'bogie_rear',
		ROTOR_MAIN = 'rotor_main',
		ROTOR_REAR = 'rotor_rear',
		ROTOR_MAIN_2 = 'rotor_main_2',
		ROTOR_REAR_2 = 'rotor_rear_2',
		ELEVATORS = 'elevators',
		TAIL = 'tail',
		OUTRIGGERS_L = 'outriggers_l',
		OUTRIGGERS_R = 'outriggers_r',
		ROPE_ATTACH_A = 'rope_attach_a',
		ROPE_ATTACH_B = 'rope_attach_b',
		PROP_1 = 'prop_1',
		PROP_2 = 'prop_2',
		ELEVATOR_L = 'elevator_l',
		ELEVATOR_R = 'elevator_r',
		RUDDER_L = 'rudder_l',
		RUDDER_R = 'rudder_r',
		PROP_3 = 'prop_3',
		PROP_4 = 'prop_4',
		PROP_5 = 'prop_5',
		PROP_6 = 'prop_6',
		PROP_7 = 'prop_7',
		PROP_8 = 'prop_8',
		RUDDER_2 = 'rudder_2',
		AILERON_L = 'aileron_l',
		AILERON_R = 'aileron_r',
		AIRBRAKE_L = 'airbrake_l',
		AIRBRAKE_R = 'airbrake_r',
		WING_L = 'wing_l',
		WING_R = 'wing_r',
		WING_LR = 'wing_lr',
		WING_RR = 'wing_rr',
		ENGINE_L = 'engine_l',
		ENGINE_R = 'engine_r',
		NOZZLES_F = 'nozzles_f',
		NOZZLES_R = 'nozzles_r',
		AFTERBURNER = 'afterburner',
		WINGTIP_1 = 'wingtip_1',
		WINGTIP_2 = 'wingtip_2',
		GEAR_DOOR_FL = 'gear_door_fl',
		GEAR_DOOR_FR = 'gear_door_fr',
		GEAR_DOOR_RL1 = 'gear_door_rl1',
		GEAR_DOOR_RR1 = 'gear_door_rr1',
		GEAR_DOOR_RL2 = 'gear_door_rl2',
		GEAR_DOOR_RR2 = 'gear_door_rr2',
		GEAR_DOOR_RML = 'gear_door_rml',
		GEAR_DOOR_RMR = 'gear_door_rmr',
		GEAR_F = 'gear_f',
		GEAR_RL = 'gear_rl',
		GEAR_LM1 = 'gear_lm1',
		GEAR_RR = 'gear_rr',
		GEAR_RM1 = 'gear_rm1',
		GEAR_RM = 'gear_rm',
		PROP_LEFT = 'prop_left',
		PROP_RIGHT = 'prop_right',
		LEGS = 'legs',
		ATTACH_MALE = 'attach_male',
		DRAFT_ANIMAL_ATTACH_LR = 'draft_animal_attach_lr',
		DRAFT_ANIMAL_ATTACH_RR = 'draft_animal_attach_rr',
		DRAFT_ANIMAL_ATTACH_LM = 'draft_animal_attach_lm',
		DRAFT_ANIMAL_ATTACH_RM = 'draft_animal_attach_rm',
		DRAFT_ANIMAL_ATTACH_LF = 'draft_animal_attach_lf',
		DRAFT_ANIMAL_ATTACH_RF = 'draft_animal_attach_rf',
		WHEELCOVER_L = 'wheelcover_l',
		WHEELCOVER_R = 'wheelcover_r',
		BARRACKS = 'barracks',
		PONTOON_L = 'pontoon_l',
		PONTOON_R = 'pontoon_r',
		NO_PED_COL_STEP_L = 'no_ped_col_step_l',
		NO_PED_COL_STRUT_1_L = 'no_ped_col_strut_1_l',
		NO_PED_COL_STRUT_2_L = 'no_ped_col_strut_2_l',
		NO_PED_COL_STEP_R = 'no_ped_col_step_r',
		NO_PED_COL_STRUT_1_R = 'no_ped_col_strut_1_r',
		NO_PED_COL_STRUT_2_R = 'no_ped_col_strut_2_r',
		LIGHT_COVER = 'light_cover',
		EMISSIVES = 'emissives',
		NEON_L = 'neon_l',
		NEON_R = 'neon_r',
		NEON_F = 'neon_f',
		NEON_B = 'neon_b',
		DASHGLOW = 'dashglow',
		DOORLIGHT_LF = 'doorlight_lf',
		DOORLIGHT_RF = 'doorlight_rf',
		DOORLIGHT_LR = 'doorlight_lr',
		DOORLIGHT_RR = 'doorlight_rr',
		UNKNOWN_ID = 'unknown_id',
		DIALS = 'dials',
		ENGINEBLOCK = 'engineblock',
		BOBBLE_HEAD = 'bobble_head',
		BOBBLE_BASE = 'bobble_base',
		BOBBLE_HAND = 'bobble_hand',
		CHASSIS_CONTROL = 'chassis_Control',
	}

	const enum VehicleClasses {
		COMPACTS,
		SEDANS,
		SUVS,
		COUPES,
		MUSCLE,
		SPORTS_CLASSIC,
		SPORTS,
		SUPER,
		MOTORCYCLES,
		OFF_ROAD,
		INDUSTRIAl,
		UTILITY,
		VANS,
		CYCLES,
		BOATS,
		HELICOPTERS,
		PLANES,
		SERVICE,
		EMERGENCY,
		MILITARY,
		COMMERCIAl,
		TRAINS
	}

	const enum VehicleColorsHex {
	}
	
	const enum VehicleFlags {
		PRESSINGHORN = 1,
		SHOOTING = 2,
		SIRENACTIVE = 4,
		VEHICLEDEAD = 8,
		AIMING = 16,
		DRIVER = 32,
		HASAIMDATA = 64,
		BURNOUT = 128,
		EXITINGFVEHICLE = 256,
		PLAYERDEAD = 512
	}

	const enum VehicleMods {
		SPOILERS = 0,
		FRONT_BUMPER = 1,
		REAR_BUMPER = 2,
		SIDE_SKIRT = 3,
		EXHAUST = 4,
		FRAME = 5,
		GRILLE = 6,
		HOOD = 7,
		FENDER = 8,
		RIGHT_FENDER = 9,
		ROOF = 10,
		ENGINE = 11,
		BRAKES = 12,
		TRANSMISSION = 13,
		/** 0 to 51 */
		HORNS = 14,
		SUSPENSION = 15,
		ARMOR = 16,
		TURBO = 18,
		XENON = 22,
		FRONT_WHEELS = 23,
		UTIL_SHADOW_SILVER = 20,
		/** Only for Motorcycles */
		BACK_WHEELS = 24,
		PLATE_HOLDERS = 25,
		TRIM_DESIGN = 27,
		ORNAMENTS = 28,
		DIAL_DESIGN = 30,
		STEERING_WHEEL = 33,
		SHIFT_LEVER = 34,
		PLAQUES = 35,
		HYDRAULICS = 38,
		BOOST = 40,
		WINDOW_TINT = 55,
		LIVERY = 48,
		PLATE = 62,
		/** 0 to 74 */
		COLOUR_1 = 66,
		/** 0 to 74 */
		COLOUR_2 = 67,
	}

	/**
	 * Wikipedia: [https://wiki.rage.mp/index.php?title=Weather](https://wiki.rage.mp/index.php?title=Weather)
	 */
	const enum Weather {
		/**
		 * ![EXTRASUNNY](https://wiki.rage.mp/images/8/8b/280px-weather_0_day.png)
		 */
		EXTRASUNNY = 0,
		/**
		 * ![CLEAR](https://wiki.rage.mp/images/d/d3/280px-weather_1_day.png)
		 */
		CLEAR = 1,
		/**
		 * ![CLOUDS](https://wiki.rage.mp/images/8/81/280px-weather_2_day.png)
		 */
		CLOUDS = 2,
		/**
		 * ![SMOG](https://wiki.rage.mp/images/4/4b/280px-weather_3_day.png)
		 */
		SMOG = 3,
		/**
		 * ![FOGGY](https://wiki.rage.mp/images/5/51/280px-weather_4_day.png)
		 */
		FOGGY = 4,
		/**
		 * ![OVERCAST](https://wiki.rage.mp/images/e/ed/280px-weather_5_day.png)
		 */
		OVERCAST = 5,
		/**
		 * ![RAIN](https://wiki.rage.mp/images/8/8e/280px-weather_6_day.png)
		 */
		RAIN = 6,
		/**
		 * ![THUNDER](https://wiki.rage.mp/images/4/42/280px-weather_7_day.png)
		 */
		THUNDER = 7,
		/**
		 * ![CLEARING](https://wiki.rage.mp/images/7/75/280px-weather_8_day.png)
		 */
		CLEARING = 8,
		/**
		 * ![NEUTRAL](https://wiki.rage.mp/images/c/c8/280px-weather_9_day.png)
		 */
		NEUTRAL = 9,
		/**
		 * ![SNOW](https://wiki.rage.mp/images/3/3d/280px-weather_10_day.png)
		 */
		SNOW = 10,
		/**
		 * ![BLIZZARD](https://wiki.rage.mp/images/0/06/280px-weather_11_day.png)
		 */
		BLIZZARD = 11,
		/**
		 * ![SNOWLIGHT](https://wiki.rage.mp/images/a/ad/280px-weather_12_day.png)
		 */
		SNOWLIGHT = 12,
		/**
		 * Set serverside to leave snow on the ground (capital letter)
		 *
		 * ![XMAS](https://wiki.rage.mp/images/6/65/280px-weather_13_day.png)
		 */
		XMAS = 13,
		/**
		 * ![HALLOWEEN](https://wiki.rage.mp/images/5/5b/280px-weather_14_day.png)
		 */
		HALLOWEEN = 14
	}
}
